// Generated by flow/def/gen_chip.py -- do not edit.
//
// The internal buses are real vectors.  They used to be four
// scalar wires each, because the reader resolved a bit-select to
// its BASE name: `.A0(w[0])` and `.A1(w[1])` both landed on a net
// called `w`, which collapsed the bus to 1 bit AND shorted its
// bits together.  Fixed in interchange item 2, and written the
// normal way here so the vehicle covers it.
//
// The PORTS are still scalar (A0..A3): BUDA models one pin per
// port name, so a vector port is the remaining half of that item.
//
// LEAF is declared with an EMPTY body.  That is how a netlist
// states a hard macro's port directions while leaving its geometry
// to the LEF, and it is also what the reader needs: an instance of
// an *undefined* module is skipped as a standard cell (the
// heuristic that keeps a million gates out of the hierarchy), so a
// blackbox macro would never reach the component table at all.

module LEAF (A, Z);
  input  [3:0] A;
  output [3:0] Z;
endmodule

module blk (I, O);
  input  [3:0] I;
  output [3:0] O;
  wire   [3:0] w;
  LEAF lo (.A(I), .Z(w));
  LEAF hi (.A(w), .Z(O));
endmodule

module quad (I, O);
  input  [3:0] I;
  output [3:0] O;
  wire   [3:0] m;
  blk bl (.I(I), .O(m));
  blk br (.I(m), .O(O));
endmodule

module chip (din, dout);
  input  [3:0] din;
  output [3:0] dout;
  wire   [3:0] c;
  quad u_q0 (.I(din), .O(c));
  quad u_q1 (.I(c), .O(dout));
endmodule
