// Generated by flow/def/gen_chip.py -- do not edit.
//
// Scalar nets, not vectors, on purpose: BUDA's Verilog reader
// resolves a bit-select to its BASE name, so `.A0(w[0])` and
// `.A1(w[1])` would collapse a 4-bit bus into ONE net and the
// bundler would see a 1-bit bus.  Four wires say what is meant.
//
// LEAF is declared with an EMPTY body.  That is how a netlist
// states a hard macro's port directions while leaving its geometry
// to the LEF, and it is also what the reader needs: an instance of
// an *undefined* module is skipped as a standard cell (the
// heuristic that keeps a million gates out of the hierarchy), so a
// blackbox macro would never reach the component table at all.

module LEAF (A0, A1, A2, A3, Z0, Z1, Z2, Z3);
  input  A0, A1, A2, A3;
  output Z0, Z1, Z2, Z3;
endmodule

module blk (I0, I1, I2, I3, O0, O1, O2, O3);
  input  I0, I1, I2, I3;
  output O0, O1, O2, O3;
  wire   w0, w1, w2, w3;
  LEAF lo (.A0(I0), .A1(I1), .A2(I2), .A3(I3), .Z0(w0), .Z1(w1), .Z2(w2), .Z3(w3));
  LEAF hi (.A0(w0), .A1(w1), .A2(w2), .A3(w3), .Z0(O0), .Z1(O1), .Z2(O2), .Z3(O3));
endmodule

module quad (I0, I1, I2, I3, O0, O1, O2, O3);
  input  I0, I1, I2, I3;
  output O0, O1, O2, O3;
  wire   m0, m1, m2, m3;
  blk bl (.I0(I0), .I1(I1), .I2(I2), .I3(I3), .O0(m0), .O1(m1), .O2(m2), .O3(m3));
  blk br (.I0(m0), .I1(m1), .I2(m2), .I3(m3), .O0(O0), .O1(O1), .O2(O2), .O3(O3));
endmodule

module chip (din0, din1, din2, din3, dout0, dout1, dout2, dout3);
  input  din0, din1, din2, din3;
  output dout0, dout1, dout2, dout3;
  wire   c0, c1, c2, c3;
  quad u_q0 (.I0(din0), .I1(din1), .I2(din2), .I3(din3), .O0(c0), .O1(c1), .O2(c2), .O3(c3));
  quad u_q1 (.I0(c0), .I1(c1), .I2(c2), .I3(c3), .O0(dout0), .O1(dout1), .O2(dout2), .O3(dout3));
endmodule
