# Generated by tools/buda2tcl.py from flow/hbundles/06_multipin_stress.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/hbundles/06_multipin_stress.buda}
# ============================================================
# hbundles/06_multipin_stress.buda
#
# Stress test for multi-receiver (multicast) buses: every bus
# here has 3, 4, 5, or 6 pins (1 driver + 2..5 receivers).
# No 2-pin unicast buses.  Modelled after the b/c/d/e buses in
# hier_bundle2.buda, scaled to the same 3×2 grid as 05.
#
# Bus style (mirrors hier_bundle2):
#   3-pin  (b-style)  — pure cross-blk fan
#   4-pin  (c-style)  — mixed: one intra-blk receiver + cross-blk
#   5-pin  (d-style)  — mixed: intra-sub or intra-blk + cross-blk
#   6-pin  (e-style)  — intra-blk fan + cross-blk receivers
#
# Cell structure / floorplan: identical to 05_stress_grid.
#
#   blk_cell  300×230  (6 instances: u1..u6, 3-col × 2-row grid)
#   sub_cell  120× 90  (4 per blk: s1 top-left, s2 top-right,
#                                  s3 bot-left, s4 bot-right)
#   leaf_cell  45× 50  (2 per sub: l left, r right)
#
#   col →     C0 (x= 50)   C1 (x=400)   C2 (x=750)
#   row 0     u1            u2            u3
#   row 1     u4            u5            u6
#
# Buses:
#
#   Depth-0 multicast (cross-blk only):
#     3-pin (×4): mp3_a..d
#     4-pin (×3): mp4_a..c
#     5-pin (×2): mp5_a..b
#     6-pin (×2): mp6_a..b
#
#   Depth-1 cell-level multicast (intra-blk, all 6 instances):
#     3-pin template: d1_mp3   s2/r → s1/r, s4/l
#     4-pin template: d1_mp4   s1/r → s2/l, s3/l, s4/l
#     5-pin template: d1_mp5   s3/l → s3/r, s1/l, s2/l, s4/l
#     6-pin template: d1_mp6   s4/r → s1/l, s2/l, s3/l, s1/r, s2/r
#
# Pipeline result (observed, after single-bundle-per-net dedup):
#   35 HBundles (D0:11 D1:24), 463 candidates, 35 expanded wrappers
#   151 segments placed; 18 NUTS overlaps (congested by design — was 271
#   before dedup, when every cross-block net was also routed at each
#   ancestor depth)
#
# ============================================================

source [file join $::corpus::root {tracks/tracks.tcl}]

buda::corner_margin {dx} {5} {dy} {5}
buda::set_min_stub_length {2}

# ── BDB: cell sizes ────────────────────────────────────────
buda::open_bdb {:memory:}

buda::add_cell {blk_cell} {300} {230}
buda::add_cell {sub_cell} {120} {90}
buda::add_cell {leaf_cell} {45} {50}

# ── BDB: cell hierarchy ────────────────────────────────────
buda::add_inst_to_cell {blk_cell} {s1} {sub_cell} {15} {15}
buda::add_inst_to_cell {blk_cell} {s2} {sub_cell} {155} {15}
buda::add_inst_to_cell {blk_cell} {s3} {sub_cell} {15} {125}
buda::add_inst_to_cell {blk_cell} {s4} {sub_cell} {155} {125}

buda::add_inst_to_cell {sub_cell} {l} {leaf_cell} {10} {20}
buda::add_inst_to_cell {sub_cell} {r} {leaf_cell} {65} {20}

# ── BDB: place top-level instances (3-col × 2-row grid) ────
buda::add_inst {u1} {blk_cell} {-} {50} {50}
buda::add_inst {u2} {blk_cell} {-} {400} {50}
buda::add_inst {u3} {blk_cell} {-} {750} {50}
buda::add_inst {u4} {blk_cell} {-} {50} {330}
buda::add_inst {u5} {blk_cell} {-} {400} {330}
buda::add_inst {u6} {blk_cell} {-} {750} {330}

# ── Derive busterms (all three levels) ────────────────────
buda::derive_busterms {2}

# ── Populate floorplan with blocks at all routing levels ───
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}

# ── Buses (written to BDB) ─────────────────────────────────
buda::bdb_net_mode {on}

# ── Depth-0: cross-blk multicast buses ─────────────────────
# b-style: pure cross-blk, 2 receivers

# 3-pin ── horizontal row fans (widest, least routing stretch)
buda::add_bus {mp3_a[8]} {u1/s1/r.out} {u2/s1/l.in,u3/s1/l.in}
buda::add_bus {mp3_b[8]} {u4/s2/r.out} {u5/s1/l.in,u6/s1/l.in}

# 3-pin ── vertical + diagonal spreads
buda::add_bus {mp3_c[4]} {u3/s3/l.out} {u4/s3/l.in,u6/s3/l.in}
buda::add_bus {mp3_d[4]} {u2/s3/l.out} {u5/s3/l.in,u1/s3/l.in}

# c-style: one intra-blk receiver + cross-blk receivers (like c1/c2)

# 4-pin ── one receiver in same blk as driver, two in different blks
buda::add_bus {mp4_a[4]} {u1/s2/r.out} {u1/s4/r.in,u2/s2/l.in,u3/s2/l.in}
buda::add_bus {mp4_b[4]} {u3/s3/l.out} {u3/s4/l.in,u4/s4/l.in,u6/s4/l.in}
buda::add_bus {mp4_c[4]} {u5/s1/r.out} {u5/s3/l.in,u2/s1/l.in,u6/s1/l.in}

# d-style: intra-sub or intra-blk receiver + multiple cross-blk (like d1/d2)

# 5-pin ── driver fans into its own blk AND multiple remote blks
buda::add_bus {mp5_a[2]} {u1/s2/l.out} {u1/s4/l.in,u4/s2/l.in,u4/s3/r.in,u4/s4/l.in}
buda::add_bus {mp5_b[2]} {u6/s4/r.out} {u6/s1/r.in,u1/s4/r.in,u2/s4/r.in,u3/s4/r.in}

# e-style: intra-blk fan to all 4 subs + cross-blk receivers (like e1/e2)

# 6-pin ── broad intra-blk fan plus cross-blk tail
buda::add_bus {mp6_a[2]} {u1/s1/l.out} {u1/s2/l.in,u1/s3/l.in,u1/s4/l.in,u4/s1/l.in,u5/s1/l.in}
buda::add_bus {mp6_b[2]} {u6/s1/l.out} {u6/s2/l.in,u6/s3/l.in,u6/s4/l.in,u3/s1/l.in,u2/s1/l.in}

# ── Depth-1: intra-blk cell-level multicast ────────────────
# Each template is written for all 6 blk instances so the
# HierarchicalBundler detects the shared pattern and creates
# one cell-level HBundle per template.

# d1_mp3 (3-pin): s2/r → s1/r, s4/l  (top-right → top-left + bot-right)
buda::add_bus {d1_mp3_u1[4]} {u1/s2/r.out} {u1/s1/r.in,u1/s4/l.in}
buda::add_bus {d1_mp3_u2[4]} {u2/s2/r.out} {u2/s1/r.in,u2/s4/l.in}
buda::add_bus {d1_mp3_u3[4]} {u3/s2/r.out} {u3/s1/r.in,u3/s4/l.in}
buda::add_bus {d1_mp3_u4[4]} {u4/s2/r.out} {u4/s1/r.in,u4/s4/l.in}
buda::add_bus {d1_mp3_u5[4]} {u5/s2/r.out} {u5/s1/r.in,u5/s4/l.in}
buda::add_bus {d1_mp3_u6[4]} {u6/s2/r.out} {u6/s1/r.in,u6/s4/l.in}

# d1_mp4 (4-pin): s1/r → s2/l, s3/l, s4/l  (top-left fans to all others)
buda::add_bus {d1_mp4_u1[4]} {u1/s1/r.out} {u1/s2/l.in,u1/s3/l.in,u1/s4/l.in}
buda::add_bus {d1_mp4_u2[4]} {u2/s1/r.out} {u2/s2/l.in,u2/s3/l.in,u2/s4/l.in}
buda::add_bus {d1_mp4_u3[4]} {u3/s1/r.out} {u3/s2/l.in,u3/s3/l.in,u3/s4/l.in}
buda::add_bus {d1_mp4_u4[4]} {u4/s1/r.out} {u4/s2/l.in,u4/s3/l.in,u4/s4/l.in}
buda::add_bus {d1_mp4_u5[4]} {u5/s1/r.out} {u5/s2/l.in,u5/s3/l.in,u5/s4/l.in}
buda::add_bus {d1_mp4_u6[4]} {u6/s1/r.out} {u6/s2/l.in,u6/s3/l.in,u6/s4/l.in}

# d1_mp5 (5-pin): s3/l → s3/r, s1/l, s2/l, s4/l
#   (bot-left fans across its own sub then up and across)
buda::add_bus {d1_mp5_u1[2]} {u1/s3/l.out} {u1/s3/r.in,u1/s1/l.in,u1/s2/l.in,u1/s4/l.in}
buda::add_bus {d1_mp5_u2[2]} {u2/s3/l.out} {u2/s3/r.in,u2/s1/l.in,u2/s2/l.in,u2/s4/l.in}
buda::add_bus {d1_mp5_u3[2]} {u3/s3/l.out} {u3/s3/r.in,u3/s1/l.in,u3/s2/l.in,u3/s4/l.in}
buda::add_bus {d1_mp5_u4[2]} {u4/s3/l.out} {u4/s3/r.in,u4/s1/l.in,u4/s2/l.in,u4/s4/l.in}
buda::add_bus {d1_mp5_u5[2]} {u5/s3/l.out} {u5/s3/r.in,u5/s1/l.in,u5/s2/l.in,u5/s4/l.in}
buda::add_bus {d1_mp5_u6[2]} {u6/s3/l.out} {u6/s3/r.in,u6/s1/l.in,u6/s2/l.in,u6/s4/l.in}

# d1_mp6 (6-pin): s4/r → s1/l, s2/l, s3/l, s1/r, s2/r
#   (bot-right fans to all other subs — two receive pins in s1 and s2)
buda::add_bus {d1_mp6_u1[2]} {u1/s4/r.out} {u1/s1/l.in,u1/s2/l.in,u1/s3/l.in,u1/s1/r.in,u1/s2/r.in}
buda::add_bus {d1_mp6_u2[2]} {u2/s4/r.out} {u2/s1/l.in,u2/s2/l.in,u2/s3/l.in,u2/s1/r.in,u2/s2/r.in}
buda::add_bus {d1_mp6_u3[2]} {u3/s4/r.out} {u3/s1/l.in,u3/s2/l.in,u3/s3/l.in,u3/s1/r.in,u3/s2/r.in}
buda::add_bus {d1_mp6_u4[2]} {u4/s4/r.out} {u4/s1/l.in,u4/s2/l.in,u4/s3/l.in,u4/s1/r.in,u4/s2/r.in}
buda::add_bus {d1_mp6_u5[2]} {u5/s4/r.out} {u5/s1/l.in,u5/s2/l.in,u5/s3/l.in,u5/s1/r.in,u5/s2/r.in}
buda::add_bus {d1_mp6_u6[2]} {u6/s4/r.out} {u6/s1/l.in,u6/s2/l.in,u6/s3/l.in,u6/s1/r.in,u6/s2/r.in}

# ── HBundle pipeline ───────────────────────────────────────
buda::run_hier_bundler {depth} {2}

buda::generate_hier_topologies

buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {signal_tracks}

buda::run_nuts
buda::negotiate_congestion
buda::ripup_reroute

# Full glory (bb :-)
buda::run_detailed_nuts
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design

buda::visualize

corpus::end [info script]
