# Generated by tools/buda2tcl.py from flow/hbundles/08_cross_level.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/hbundles/08_cross_level.buda}
# ============================================================
# hbundles/08_cross_level.buda
#
# Clone of 04_deep_hierarchy.buda extended with buses that
# intentionally connect endpoints at DIFFERENT hierarchy depths
# (cross-level buses).  Tests the HierarchicalBundler's ability
# to classify and route nets where driver and receiver terminate
# at different levels of the cell hierarchy.
#
# Same cell structure and floorplan as 04:
#   chip_cell  400×500  (depth 0, 2 instances: left, right)
#   blk_cell   180×230  (depth 1, 2 per chip: top, bot)
#   leaf_cell   70×130  (depth 2, 2 per blk: lo, hi)
#
# Absolute block positions (same as 04):
#   left  (0,0)–(400,500)    left/top   (10,260)–(190,490)
#                              left/bot   (10, 10)–(190,240)
#   right (450,0)–(850,500)  right/top  (460,260)–(640,490)
#                              right/bot  (460, 10)–(640,240)
#   Leaves (lo=left half, hi=right half within each blk):
#     left/top/lo  ( 20,310)–( 90,440)   left/top/hi  (100,310)–(170,440)
#     left/bot/lo  ( 20, 60)–( 90,190)   left/bot/hi  (100, 60)–(170,190)
#     right/top/lo (470,310)–(540,440)  right/top/hi  (550,310)–(620,440)
#     right/bot/lo (470, 60)–(540,190)  right/bot/hi  (550, 60)–(620,190)
#
# Buses:
#
#   Same-level buses (from 04, unchanged):
#     x_top      left/top/hi  → right/top/lo    D0 cross-chip, leaf→leaf
#     x_bot      left/bot/hi  → right/bot/lo    D0 cross-chip, leaf→leaf
#     l_tb       left/top/lo  → left/bot/hi     D1 intra-chip, leaf→leaf
#     b_lohi_*   lo           → hi              D2 intra-blk,  leaf→leaf  (×4)
#
#   Cross-level buses (new, D1 blk ↔ D2 leaf):
#     xl_b2l_ht  left/top     → right/top/lo    blk→leaf, cross-chip, horizontal top
#     xl_b2l_hb  left/bot     → right/bot/lo    blk→leaf, cross-chip, horizontal bot
#     xl_l2b_dt  right/top/hi → left/bot        leaf→blk, cross-chip, diagonal (top-R→bot-L)
#     xl_l2b_db  right/bot/hi → left/top        leaf→blk, cross-chip, anti-diag (bot-R→top-L)
#     xl_ic_b2l  left/top     → left/bot/lo     blk→leaf, intra-chip, downward
#     xl_ic_l2b  left/bot/hi  → left/top        leaf→blk, intra-chip, upward
#
#   Extreme cross-level buses (D0 chip ↔ D2 leaf):
#     xl_c2l     left         → right/bot/hi    chip→leaf, cross-chip
#     xl_l2c     right/top/hi → right           leaf→chip, intra-right-chip
#
# Pipeline result:
#   14 HBundles (D0:7 D1:3 D2:4) — one per bus (each net bundled exactly
#   once at its most specific endpoints; level = common-ancestor depth).
#   14 expanded wrappers; 19 segments placed; 0 NUTS overlaps
#   check_design: Success — no violations found (nuts and dnuts).
#
#   Bundle classification:
#     D0: xl_b2l_ht  (left/top→right/top/lo)     [D1→D2 cross-chip]
#         xl_b2l_hb  (left/bot→right/bot/lo)     [D1→D2 cross-chip]
#         xl_l2b_dt  (right/top/hi→left/bot)     [D2→D1 cross-chip diagonal]
#         xl_l2b_db  (right/bot/hi→left/top)     [D2→D1 cross-chip anti-diag]
#         xl_c2l     (left→right/bot/hi)          [D0→D2 cross-chip]
#         x_top      (left/top/hi→right/top/lo)  same-level cross-chip
#         x_bot      (left/bot/hi→right/bot/lo)  same-level cross-chip
#     D1: xl_ic_b2l  (left/top→left/bot/lo)      [D1→D2 intra-chip]
#         xl_ic_l2b  (left/bot/hi→left/top)      [D2→D1 intra-chip]
#         l_tb       (left/top/lo→left/bot/hi)   same-level intra-chip
#     D2: b_lohi ×4  (lo→hi)  blk_cell template + 3 replicas → 4 instances
#     Note: xl_l2c (right/top/hi→right) is degenerate (receiver is ancestor
#           of driver) and silently dropped; not yet supported.
#
# ============================================================

source [file join $::corpus::root {tracks/tracks.tcl}]

buda::corner_margin {dx} {5} {dy} {5}
buda::set_min_stub_length {2}

# ── BDB: cell sizes ────────────────────────────────────────
buda::open_bdb {:memory:}
# open_bdb 08fp.bdb

buda::add_cell {chip_cell} {400} {500}
buda::add_cell {blk_cell} {180} {230}
buda::add_cell {leaf_cell} {70} {130}

# ── BDB: cell hierarchy ────────────────────────────────────
buda::add_inst_to_cell {chip_cell} {top} {blk_cell} {10} {260}
buda::add_inst_to_cell {chip_cell} {bot} {blk_cell} {10} {10}

buda::add_inst_to_cell {blk_cell} {lo} {leaf_cell} {10} {50}
buda::add_inst_to_cell {blk_cell} {hi} {leaf_cell} {90} {50}

# ── BDB: place top-level instances ────────────────────────
buda::add_inst {left} {chip_cell} {-} {0} {0}
buda::add_inst {right} {chip_cell} {-} {450} {0}

# ── Derive busterms (all three levels) ────────────────────
buda::derive_busterms {2}

# ── Populate floorplan with blocks at all routing levels ───
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}

# ── Buses (written to BDB) ─────────────────────────────────
buda::bdb_net_mode {on}

# ── Same-level buses (from 04, unchanged) ──────────────────

# Depth-0 cross-chip buses (leaf→leaf)
buda::add_bus {x_top[4]} {left/top/hi.out} {right/top/lo.in}
buda::add_bus {x_bot[4]} {left/bot/hi.out} {right/bot/lo.in}

# Depth-1 intra-chip bus (leaf→leaf, top to bot)
buda::add_bus {l_tb[4]} {left/top/lo.out} {left/bot/hi.in}

# Depth-2 intra-blk buses (leaf→leaf, lo to hi — all 4 blk instances)
buda::add_bus {b_lohi_lt[4]} {left/top/lo.out} {left/top/hi.in}
buda::add_bus {b_lohi_lb[4]} {left/bot/lo.out} {left/bot/hi.in}
buda::add_bus {b_lohi_rt[4]} {right/top/lo.out} {right/top/hi.in}
buda::add_bus {b_lohi_rb[4]} {right/bot/lo.out} {right/bot/hi.in}

# ── Cross-level buses: D1 blk ↔ D2 leaf ───────────────────
# These have one endpoint at blk depth (depth 1) and the other
# at leaf depth (depth 2), testing the bundler's handling of
# mixed-depth endpoint classification.

# blk→leaf, cross-chip (left blk drives right leaf)
buda::add_bus {xl_b2l_ht[4]} {left/top.out} {right/top/lo.in}
buda::add_bus {xl_b2l_hb[4]} {left/bot.out} {right/bot/lo.in}

# leaf→blk, cross-chip (right leaf drives left blk input)
buda::add_bus {xl_l2b_dt[4]} {right/top/hi.out} {left/bot.in}
buda::add_bus {xl_l2b_db[4]} {right/bot/hi.out} {left/top.in}

# blk→leaf, intra-chip (within left: top blk drives bot leaf)
buda::add_bus {xl_ic_b2l[4]} {left/top.out} {left/bot/lo.in}

# leaf→blk, intra-chip (within left: bot leaf drives top blk input)
buda::add_bus {xl_ic_l2b[4]} {left/bot/hi.out} {left/top.in}

# ── Extreme cross-level buses: D0 chip ↔ D2 leaf ──────────
# Chip-boundary endpoint paired with a leaf endpoint —
# the most distant combination in the three-level hierarchy.

# chip→leaf, cross-chip (left chip-level output to right leaf)
buda::add_bus {xl_c2l[4]} {left.out} {right/bot/hi.in}

# leaf→chip, intra-chip (right leaf feeds right chip-level input)
buda::add_bus {xl_l2c[4]} {right/top/hi.out} {right.in}

# b6 uses this detour, but dnuts has a problem finding tracks
buda::detour_channel {S} {100}

# ── HBundle pipeline ───────────────────────────────────────
buda::run_hier_bundler {depth} {2}

buda::generate_hier_topologies

buda::run_planner {hier} {5}

buda::run_nuts

buda::check_design {nuts}

buda::run_detailed_nuts
buda::check_design {dnuts}

buda::visualize

corpus::end [info script]
