# Generated by tools/buda2tcl.py from flow/hbundles/09_local_global_compete.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/hbundles/09_local_global_compete.buda}
# ============================================================
# hbundles/09_local_global_compete.buda
#
# Local/global competition: a wide cell-local bus (D1) and a global
# cross-chip bus (D0) both want the band over the cell interior.
#
#   gsrc (0,0)-(150,600)        gdst (850,0)-(1000,600)
#   proc = proc_cell @ (300,200), 400x250 -> abs (300,200)-(700,450)
#     lo  (20,40)-(120,210) cell-local -> abs (320,240)-(420,410)
#     hi (280,40)-(380,210) cell-local -> abs (580,240)-(680,410)
#
# Bands (y): [0,200] [200,240] [240,410] [410,450] [450,600]
#   local  loc[32]: eff 136 on M6 — fits ONLY band [240,410] (cap 170)
#   global g[24]:   eff 102 on M6 — fits [0,200], [240,410], or [450,600]
#
# The global is planned first (D0) and its window centre lands in
# [240,410] — without the demand reservation it takes the local's only
# band and the local must rip it up afterwards.  With the reservation
# (parked when run_planner hier expands the cell bundle), the global
# sees the cell interior as spoken for and picks [0,200] directly:
# no rip-up, everything overflow-free in one pass.
# ============================================================

source [file join $::corpus::root {tracks/tracks.tcl}]

# ── BDB: cells and hierarchy ───────────────────────────────
buda::open_bdb {:memory:}

buda::add_cell {gend_cell} {150} {600}
buda::add_cell {proc_cell} {400} {250}
buda::add_cell {leaf_cell} {100} {170}

buda::add_inst_to_cell {proc_cell} {lo} {leaf_cell} {20} {40}
buda::add_inst_to_cell {proc_cell} {hi} {leaf_cell} {280} {40}

buda::add_inst {gsrc} {gend_cell} {-} {0} {0}
buda::add_inst {gdst} {gend_cell} {-} {850} {0}
buda::add_inst {proc} {proc_cell} {-} {300} {200}

buda::derive_busterms {1}

buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}

# ── Buses ──────────────────────────────────────────────────
buda::bdb_net_mode {on}

# Global cross-chip bus (D0) — crosses over the proc cell.
buda::add_bus {g[24]} {gsrc.out} {gdst.in}

# Wide cell-local bus (D1) — confined to the proc interior.
buda::add_bus {loc[32]} {proc/lo.out} {proc/hi.in}

# ── HBundle pipeline ───────────────────────────────────────
buda::run_hier_bundler {depth} {1}

buda::generate_hier_topologies

buda::run_planner {hier} {5}

buda::run_nuts

buda::check_design {nuts}

buda::run_detailed_nuts
buda::check_design {dnuts}
buda::visualize

corpus::end [info script]
