# Generated by tools/buda2tcl.py from flow/rv/soc_conv_div.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/rv/soc_conv_div.buda}
# ============================================================
# flow/rv/soc_conv_div.buda
#
# soc.buda with the bundler asked for TWO relations at once:
#
#   run_hier_bundler depth 4 CONVERGENT DIVERGENT
#
# A strategy names one relation, which is enough until a design
# carries more than one SHAPE.  This one does, in both directions:
#
#   boot[0..31]   32 die pads  ->  u_imem       a fan-IN
#   dbg[0..31]    u_ixb/u_dmux ->  32 die pads  a fan-OUT
#
# CONVERGENT bundles the first and splits the second; DIVERGENT
# does exactly the opposite.  Neither bundles both, and COMBINED
# is the join of CONVERGENT and BIDIRECTIONAL, so it does not
# either.  Naming the SET gets both — the union-find join already
# worked over a set of relations; only the way to ask was missing.
#
#   strategy               bundles   abstract WL    detailed WL
#   STRICT                     127    31,234,654    409,819,470
#   CONVERGENT                  89    29,771,517    447,753,870
#   DIVERGENT                   78    19,104,008    427,958,400
#   CONVERGENT DIVERGENT        40    16,766,857    453,430,400
#
# Every one of them ends clean with 0 unplaced bits.  The trend is
# the honest summary: the more you bundle, the more trunk is
# shared (abstract WL down 46% at the join) and the further each
# tree has to reach to its leaves (detailed WL up 15%).  Which
# point on that curve a design wants is the design's call, which
# is why this is a fourth script and not a change to soc.buda.
#
# Regenerate the three input files with: python3 flow/rv/gen_soc.py
# ============================================================

buda::open_bdb {:memory:}

buda::set_import_scale {dbu}
buda::set_unit_check {on}

buda::corner_margin {dx} {3000} {dy} {3000}
buda::set_min_stub_length {1000}

buda::import_lef_tech {soc.lef}
buda::import_def_lef {soc.def} {soc.lef}
buda::import_verilog {soc.v}
buda::derive_container_bboxes {margin} {4000}

buda::derive_busterms {4}

buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::add_blocks_from_bdb {3} {skip}
buda::add_blocks_from_bdb {4} {skip}

# The one line that differs from soc.buda.
buda::run_hier_bundler {depth} {4} {CONVERGENT} {DIVERGENT}
buda::dump_hbundles

buda::generate_hier_topologies

buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5}

buda::run_nuts
buda::check_design {nuts}

buda::run_detailed_nuts
buda::check_design {dnuts}

buda::negotiate_congestion {10}
buda::ripup_reroute {20}
buda::refine_selection

buda::check_design {dnuts}
buda::report_wirelength

buda::visualize

corpus::end [info script]
