# Generated by tools/buda2tcl.py from flow/big_data_test/b44.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/b44.buda}
source [file join $::corpus::root {tracks/tracks4top.tcl}]
#source tc3a_flat_x10.buda

buda::add_block {blk_07} {2960} {9750} {4660} {10250}
buda::add_block {blk_23} {200} {10830} {2700} {11830}
buda::add_block {io_pad_tl} {200} {12000} {1200} {12800}

buda::add_bus {bus_060[52]} {blk_23.p} {blk_07.p,io_pad_tl.p}

buda::run_bundler
buda::generate_topologies
buda::check_design {topo} {all}

# planner selects the first topo: trunk+mst topo (topo WL = 3510)
# select_topology 1 1
buda::run_planner
buda::run_nuts
buda::run_detailed_nuts
buda::check_design
buda::report_wl
# [report_wirelength] total detailed WL = 234546 over 1 bundle(s) / 312 bit-wire(s), 0 unplaced bit(s); bit-scaled envelope [182520..632320]
# visualize

# simple L-topo comes much later (topo WL = 4010; TRUNK_V@x700 — the
# structural (wl, nsegs, type) tie-break sorts this 2-seg candidate ahead
# of its 4010-tie siblings; index 15 since the hanan_loci default flip grew
# the pool 23->35, same candidate by topo_uid)
buda::select_topology {1} {15}
buda::run_planner
buda::run_nuts
buda::run_detailed_nuts
buda::check_design
buda::report_wl
# [report_wirelength] total detailed WL = 193376 over 1 bundle(s) / 104 bit-wire(s), 0 unplaced bit(s); bit-scaled envelope [182520..260520]
# visualize

# The fix: `set_planner_param kWLSpread 0.125` (opt-in) prices realization
# risk — scored WL = nominal + kWLSpread*(wl_hi - wl_lo), the candidate's
# slide/span DOF envelope — so the wide-envelope trunk+mst (spread 8650) is
# demoted and the planner UN-pinned picks an even better candidate than the
# hand-pin above (detailed WL 188513, -19.6% vs the default's 234546).
# See docs/script_reference/planner.md (kWLSpread) and
# test/tests/test_planner_wl_spread.py.
# set_planner_param kWLSpread 0.125

corpus::end [info script]
