# Generated by tools/buda2tcl.py from flow/big_data_test/b61.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/b61.buda}
# 6 busterms, ideal topo: trunk V + trunk H + one stub
# instead of the 10 seg Trunk+MST
# let's measure the impact of a num-seg penalty..
#
# FINDINGS (kSegs experiment — set_planner_param kSegs <wl-units/segment>):
#   pinned through planner+NUTS+DNUTS (all clean, 16-bit bus):
#     topo1  TRUNK_H+MST 10 segs estWL 15940  detWL 244772  vias 144
#     topo13 TRUNK_V+MST  5 segs estWL 17480  detWL 250064  vias  64
#     topo19 TRUNK_V      4 segs estWL 19010  detWL 303436  vias  48
#     topo26 TRUNK_V      3 segs estWL 21110  detWL 307268  vias  32
#   the WL estimate exaggerates the big tree's edge (+9.7% est vs +2.2%
#   realized against the 5-seg tree, which has 56% fewer per-bit vias).
#   kSegs selects: 0->topo1, 100-300->topo2 (9 segs), 400-800->topo13,
#   1600->topo19, 2400->topo26 (the 3-seg shape described above).
#   corpus @500: big2 unplaced 108->0, overlaps 4->0, detWL +1.8%;
#   bigHalf unplaced 593->214, overlaps 3->1, detWL -3.1%, vias -29%.
# uncomment to try:
#set_planner_param kSegs 500
#
# SORT EXPERIMENT (BUDA_TOPO_SORT=segs — candidates ordered by ascending
# SEGMENT COUNT, wirelength second; the "simplest shape first" extreme):
#   b61: rank1 becomes the 3-seg TRUNK_V, but the planner's SELECTION is
#     UNCHANGED in both kSegs settings (selection is cost-driven; the sort
#     only relabels indices).
#   b44: BREAKS the index-pinned script (`select_topology 1 10` lands on a
#     different shape under the new order: 2->4 segs, 3x the vias).
#   big2 + stage-b ripup: the fewest-seg index windows heal to 0/0 but land
#     +1.1% detWL ABOVE the wirelength-ordered windows (11.957M -> 12.087M);
#     with kSegs 500 ripup is a no-op either way (11.673M, the best result).
#   verdict: kSegs is the effective lever; the sort toggle is experiment-only.
#
# HEADROOM-GATE EXPERIMENT (kSegsGate — fade the penalty with the candidate's
# peak chosen-band fill; motivated by flat kSegs=500 regressing two stressed
# flows: 07_wide_fan_stress 0/0 -> 3 unpl/2 ovl, channel_stress 3 -> 7 unpl):
#   b61/b44 (quiet): gated == flat (5-seg tree / unchanged) — gate inert.
#   07_wide_fan:  gated is WORSE THAN BASELINE (272 sel segs vs 183, 11 unpl)
#     — the gate is per-candidate, so full-band candidates pay NO penalty:
#     stress becomes attractive (a perverse incentive, not a safety valve).
#   mempool_tile: gated gives back most of flat's -54% detWL win (453K vs
#     245K, unpl 3090 vs 1756).  bigHalf/big2: worse than flat across the
#     board.  A bundle-level gate would be sound but fades the penalty
#     exactly where flat wins biggest (stress: fewer segs = less demand).
#   RESOLUTION: flat kSegs + healers dominates — ripup_reroute heals BOTH
#     flat-500 regressions to 0/0 (07: +5.8% detWL, -25% vias; channel: 0/0)
#     and keeps every win.  kSegsGate stays an opt-in experiment knob (0 =
#     flat default).
#
# RELATIVE FORMULATION + DEFAULT-FLIP AUDIT (kSegsRel = fraction of the
# design's max-possible HPWL; env BUDA_KSEGS_REL flips the default for
# study runs): full sweep tables and the gating-issue list (G1-G6) in
# docs/internal/ksegs_default_audit.md.  Headlines: channel_stress's
# absolute-500 regression was a units artifact (invariant at every alpha
# <= 0.25 relative); alpha=0.02 is the safe Pareto point (only
# 07_wide_fan_stress regresses, healed by ripup); on THIS flow 0.02-0.05
# picks the 5-seg tree, 0.1+ over-compacts to the 3-seg at +25% WL.
#   PROMOTED: 0.02 is now the COMPILED default (kDefaultKSegsRel), gated
#   on healers-ahead / no multi_trunk / no kPeak; BUDA_KSEGS_REL demotes
#   to a study override ("0" disables).  This flow does not declare
#   healersAhead, so a plain run still selects the 10-seg tree (the gate
#   stands the default down, note printed); add
#   `set_planner_param healersAhead 1` to see the 5-seg selection.
#   (Issue #444: a healer command later in the flow no longer auto-enables
#   the gate — declare the intent explicitly before run_planner.)

source [file join $::corpus::root {tracks/tracks4top.tcl}]
#source tc3a_flat_x10.buda

buda::add_block {blk_01} {10680} {2310} {13580} {3310}
buda::add_block {blk_22} {11380} {4970} {13580} {6870}
buda::add_block {blk_24} {9250} {7990} {10950} {9090}
buda::add_block {blk_29} {11580} {3780} {13580} {4680}
buda::add_block {blk_31} {200} {7990} {2700} {9190}
buda::add_block {blk_32} {4870} {9430} {7470} {10630}

buda::add_bus {bus_034[16]} {blk_32.p} {blk_01.p,blk_29.p,blk_22.p,blk_24.p,blk_31.p}

buda::run_bundler
buda::generate_topologies
buda::check_design {topo} {all}

# planner selects the first topo (1 of 29 or 30): trunk-h
# select_topology 1 1
buda::run_planner
buda::run_nuts
buda::run_detailed_nuts
buda::check_design
buda::report_wl
buda::visualize

corpus::end [info script]
