# Generated by tools/buda2tcl.py from flow/big_data_test/big.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big.buda}
source [file join $::corpus::root {tracks/tracks4top.tcl}]
source [file join $::corpus::root {big_data_test/tc3a_flat_x10.tcl}]
buda::run_bundler
buda::generate_topologies
buda::check_design {topo} {all}
# design is already clean so no need for track level accuracy
# run_planner signal_tracks
buda::run_planner
buda::run_nuts
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design
buda::visualize

corpus::end [info script]
