# Generated by tools/buda2tcl.py from flow/big_data_test/big_3bundles_sel_pure_mst_topo.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big_3bundles_sel_pure_mst_topo.buda}
# big3.buda — bundles 57/46/50 extracted from big.buda
# bundle 57 = bus_030 (48 wide), bundle 50 = bus_047 (84 wide), bundle 46 = bus_069 (18 wide)
# Full floorplan kept so topology generation (Hanan grid / pass-through) matches the full run.
# Renumbered in source order: bundle 1 = bus_030, bundle 2 = bus_047, bundle 3 = bus_069.

source [file join $::corpus::root {tracks/tracks4top.tcl}]
source [file join $::corpus::root {big_data_test/tc3a_flat_x10_blocks.tcl}]

# --- bundle 1 (was 57)
buda::add_bus {bus_030[32]} {blk_29.p} {blk_22.p,blk_08.p,blk_14.p,blk_18.p}

# --- bundle 2 (was 50)
buda::add_bus {bus_047[56]} {blk_27.p} {blk_36.p,blk_11.p,blk_26.p}

# --- bundle 3 (was 46)
buda::add_bus {bus_069[12]} {blk_25.p} {blk_21.p,blk_27.p,blk_18.p,io_pad_tl.p}

buda::run_bundler
buda::generate_topologies

# Select a standalone MST (MST_HV/MST_VH) super-candidate for each bundle.
#
# `select_topology <bundle> group:<N>` pins the nominal-locus FAMILY that
# CONTAINS candidate id N (1-based) — N is the representative's candidate id, NOT
# the family's ordinal position in the `--grouped` list. Read the exact token off
# `dump_topologies <bundle> --grouped` (the `group:<N>` mark on each family row,
# emitted verbatim so you paste it straight after the bundle hint); e.g.
# bus_069's MST_HV family is `group:16`.
#
# bundle   MST family (rep type @ candidate id)
# bus_069  MST_HV @ 16   (MST_VH @ 17)
# bus_047  MST_VH @ 23   (MST_HV @ 26)
# bus_030  MST_HV @ 19   (MST_VH @ 20)
#
buda::select_topology {bus_069} {group:16}
buda::select_topology {bus_047} {group:23}
buda::select_topology {bus_030} {group:19}
buda::run_planner
buda::run_nuts
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design
buda::visualize

corpus::end [info script]
