# Generated by tools/buda2tcl.py from flow/big_data_test/bigHalf_bus038_bitrunk.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/bigHalf_bus038_bitrunk.buda}
# From bigHalf_bus005_dangling.buda
source [file join $::corpus::root {tracks/tracks4top.tcl}]
source [file join $::corpus::root {big_data_test/tc3a_flat_5x.tcl}]
buda::run_bundler
buda::generate_topologies_for_bundle {bus_038} {no_hanan_loci}
buda::dump_topologies {bus_038}
buda::check_design {topo} {all}
# The original vehicle pinned candidate 20 — the fully-degenerate legacy
# BITRUNK_H whose free-sliding trunk grazed every endpoint block untapped and
# opened all 56 bits at DNUTS.  The generation-time anchoring gate
# (filter_unanchored_bitrunk) now drops that candidate, so the pool is 19 and
# the pin is retired: the flow now demonstrates the HEALTHY default (the gate
# keeps only anchored shapes; planner picks freely, 0/0/0).  Do NOT re-add a
# blind index pin here — under `multi_trunk` (or BUDA_MULTI_TRUNK=1) the pool
# grows and a stale index lands on a degenerate tree again (the 2026-07-30
# default-flip study measured exactly that: 0/56/1 from the re-armed pin).
buda::run_planner
buda::run_nuts
buda::run_detailed_nuts
buda::check_design
buda::visualize

corpus::end [info script]
