# Generated by tools/buda2tcl.py from flow/big_data_test/bigHalf.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/bigHalf.buda}
# full rr+negotiate flow (reaches the clean 0/0 endpoint) + fine-grain check
source [file join $::corpus::root {tracks/tracks4top.tcl}]
source [file join $::corpus::root {big_data_test/tc3a_flat_5x.tcl}]
buda::run_bundler
buda::generate_topologies
buda::check_design {topo} {all}
# Heals below → opt into the kSegsRel proactive default explicitly (issue #444).
buda::set_planner_param {healersAhead} {1}
buda::run_planner {signal_tracks}
buda::run_nuts
buda::check_design {nuts}
buda::negotiate_congestion
buda::ripup_reroute {30}
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design
buda::negotiate_congestion
buda::ripup_reroute {30}
buda::check_design
buda::visualize

corpus::end [info script]
