# Generated by tools/buda2tcl.py from flow/big_data_test/tc3a_flat_x10_blocks.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/tc3a_flat_x10_blocks.buda}
buda::set_die {30000} {24000}

buda::add_block {blk_00} {2960} {7760} {4560} {9160}
buda::add_block {blk_01} {10680} {2310} {13580} {3310}
buda::add_block {blk_02} {9180} {11600} {11980} {12800}
buda::add_block {blk_03} {7810} {4240} {10710} {5140}
buda::add_block {blk_04} {6630} {200} {8130} {1200}
buda::add_block {blk_05} {2660} {6690} {3860} {7390}
buda::add_block {blk_06} {200} {9460} {2700} {10560}
buda::add_block {blk_07} {2960} {9750} {4660} {10250}
buda::add_block {blk_08} {200} {4370} {2300} {5270}
buda::add_block {blk_09} {7810} {5520} {10710} {6020}
buda::add_block {blk_10} {8090} {3050} {9690} {3950}
buda::add_block {blk_11} {2660} {3840} {3660} {5140}
buda::add_block {blk_12} {11380} {9340} {13580} {11140}
buda::add_block {blk_13} {5850} {2310} {7050} {3610}
buda::add_block {blk_14} {4920} {5340} {6820} {6540}
buda::add_block {blk_15} {4900} {6930} {7200} {8730}
buda::add_block {blk_16} {200} {1170} {2290} {3130}
buda::add_block {blk_17} {6660} {11300} {8760} {12800}
buda::add_block {blk_18} {4380} {4140} {7180} {4940}
buda::add_block {blk_19} {200} {5540} {2100} {6840}
buda::add_block {blk_20} {2960} {10900} {5960} {12800}
buda::add_block {blk_21} {8210} {6400} {10710} {7300}
buda::add_block {blk_22} {11380} {4970} {13580} {6870}
buda::add_block {blk_23} {200} {10830} {2700} {11830}
buda::add_block {blk_24} {9250} {7990} {10950} {9090}
buda::add_block {blk_25} {8260} {200} {9560} {1800}
buda::add_block {blk_26} {4890} {200} {6490} {1800}
buda::add_block {blk_27} {2660} {2370} {4860} {3670}
buda::add_block {blk_28} {7740} {9330} {10440} {10630}
buda::add_block {blk_29} {11580} {3780} {13580} {4680}
buda::add_block {blk_30} {9690} {200} {12290} {2200}
buda::add_block {blk_31} {200} {7990} {2700} {9190}
buda::add_block {blk_32} {4870} {9430} {7470} {10630}
buda::add_block {blk_33} {7740} {7490} {9140} {9090}
buda::add_block {blk_34} {200} {3400} {1400} {4100}
buda::add_block {blk_35} {2660} {200} {4760} {2100}
buda::add_block {blk_36} {8090} {2310} {10090} {2810}
buda::add_block {blk_37} {240} {7120} {2340} {7720}
buda::add_block {blk_38} {2660} {5470} {4160} {6370}
buda::add_block {blk_39} {11280} {7150} {13580} {9050}
buda::add_block {io_pad_bl} {200} {200} {1200} {1000}
buda::add_block {io_pad_br} {12580} {200} {13580} {1000}
buda::add_block {io_pad_tl} {200} {12000} {1200} {12800}
buda::add_block {io_pad_tr} {12580} {12000} {13580} {12800}

corpus::end [info script]
