# Generated by tools/buda2tcl.py from flow/big_data_test/tc3a.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/tc3a.buda}
source [file join $::corpus::root {tracks/tracks4top.tcl}]

# > 1000% congested.
# x10 expansion in tc3a_flat.buda ~= big.buda
# open_bdb tc3a.bdb.sql

# copied tc3a.bdb.sql and reduced bit count of some of the failing bundles
# E.g.,
#   tools/bdb_edit_bus.py flow/big_data_test/tc3a_bit_pruned.bdb.sql --set-bit 2 --bus bus_010
# There are a total of 72 failures out of 80! Pruned buses:
#   From 60 to 4: 003 066 075 014 077 074 012
#   From 56 to 4: 050 058 033 038 045 059 047 018 062 079 026 073 016
#   From 52 to 4: 071 068 060
#   From 48 to 4: 005 022 041 056 013
#   From 44 to 4: 072 054 010 027 025 031
#   From 40 to 4: 002 036 040 021
#   From 36 to 4: 006 032 019
#   From 32 to 4: 030 042 049
#   From 28 to 4: 001 007 004 015 035 028
#   From 24 to 4: 065 053 000 057 044
#   From 20 to 4: 048 078 051 055 076 039
#   From 16 to 4: 011 046 070 023 034
#   From 12 to 2: 008 063 069 052
#   From  8 to 2: 009 067 037 024 020
#   From  4 to 2: 043 010
buda::open_bdb {tc3a_bit_pruned.bdb.sql}

buda::derive_busterms {1}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::run_hier_bundler {depth} {1}
buda::dump_hbundles
buda::generate_hier_topologies
buda::run_planner {hier}
buda::run_nuts
# (negotiate_congestion removed: the receiver-graze coverage fix — issue #438,
#  the slide-aware block-coverage gate in verify.cpp — makes this design route
#  0/0/0 with no healing. negotiate_congestion is not only redundant here but,
#  run on the already-clean design via `source`, degrades it — a separate
#  execution-context bug in negotiate to be tracked on its own.)
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design {dnuts}
buda::visualize

corpus::end [info script]
