// Generated by flow/rv/gen_soc.py -- do not edit.
//
// A dual-core RV32-shaped SoC, five levels deep.  It is a WIRING
// vehicle: the structure, port widths and bus connections are those
// of a small core, and the arithmetic is not — `u_inc` adds pc to
// itself where a real fetch unit would add 4, because this design
// is routed, never simulated.  Nothing downstream cares what the
// bits mean; everything downstream cares how many there are and
// where they go.
//
// The leaf modules are declared as blackbox stubs WITH their port
// widths, which is what a synthesis blackbox for a macro looks
// like.  The widths are load-bearing: a port whose width is not
// declared is one bit wide as far as any reader can tell, and a
// 32-bit memory bus wired to it would arrive one bit wide.

module ADD32 (a, b, y, co);
  input [31:0] a;
  input [31:0] b;
  output [31:0] y;
  output co;
endmodule

module ALN32 (din, sz, dout);
  input [31:0] din;
  input [1:0] sz;
  output [31:0] dout;
endmodule

module BRU32 (a, b, op, taken);
  input [31:0] a;
  input [31:0] b;
  input [2:0] op;
  output taken;
endmodule

module DEC32 (instr, ctrl, rs1, rs2, rd);
  input [31:0] instr;
  output [7:0] ctrl;
  output [4:0] rs1;
  output [4:0] rs2;
  output [4:0] rd;
endmodule

module IMM32 (instr, imm);
  input [31:0] instr;
  output [31:0] imm;
endmodule

module LOG32 (a, b, op, y);
  input [31:0] a;
  input [31:0] b;
  input [1:0] op;
  output [31:0] y;
endmodule

module MUX32 (a, b, s, y);
  input [31:0] a;
  input [31:0] b;
  input s;
  output [31:0] y;
endmodule

module REG32 (d, q, en);
  input [31:0] d;
  output [31:0] q;
  input en;
endmodule

module RF32 (ra1, ra2, wa, wd, we, rd1, rd2);
  input [4:0] ra1;
  input [4:0] ra2;
  input [4:0] wa;
  input [31:0] wd;
  input we;
  output [31:0] rd1;
  output [31:0] rd2;
endmodule

module SRAM32 (addr, wdata, we, en, rdata);
  input [9:0] addr;
  input [31:0] wdata;
  input we;
  input en;
  output [31:0] rdata;
endmodule

module alu (a, b, op, y);
  input [31:0] a;
  input [31:0] b;
  input [2:0] op;
  output [31:0] y;
  wire [31:0] lgc;
  wire [31:0] sum;
  ADD32 u_add (.a(a), .b(b), .y(sum));
  LOG32 u_log (.a(a), .b(b), .op(op[1:0]), .y(lgc));
  MUX32 u_ysel (.a(sum), .b(lgc), .s(op[2]), .y(y));
endmodule

module ifu (branch_pc, take, iaddr, pc_out);
  input [31:0] branch_pc;
  input take;
  output [9:0] iaddr;
  output [31:0] pc_out;
  wire [31:0] npc;
  wire [31:0] pc;
  wire [31:0] seq;
  ADD32 u_inc (.a(pc), .b(pc), .y(seq));
  MUX32 u_nsel (.a(seq), .b(branch_pc), .s(take), .y(npc));
  REG32 u_pc (.d(npc), .q(pc), .en(take));
  ALN32 u_iab (.din(pc[11:2]), .sz(take), .dout(iaddr));
  REG32 u_pcb (.d(pc), .q(pc_out), .en(take));
endmodule

module idu (instr, ctrl, imm, rs1, rs2, rd);
  input [31:0] instr;
  output [7:0] ctrl;
  output [31:0] imm;
  output [4:0] rs1;
  output [4:0] rs2;
  output [4:0] rd;
  DEC32 u_dec (.instr(instr), .ctrl(ctrl), .rs1(rs1), .rs2(rs2), .rd(rd));
  IMM32 u_imm (.instr(instr), .imm(imm));
endmodule

module exu (rs1v, rs2v, imm, ctrl, res, take);
  input [31:0] rs1v;
  input [31:0] rs2v;
  input [31:0] imm;
  input [7:0] ctrl;
  output [31:0] res;
  output take;
  wire [31:0] opb;
  MUX32 u_bsel (.a(rs2v), .b(imm), .s(ctrl[0]), .y(opb));
  alu u_alu (.a(rs1v), .b(opb), .op(ctrl[3:1]), .y(res));
  BRU32 u_bru (.a(rs1v), .b(rs2v), .op(ctrl[6:4]), .taken(take));
endmodule

module lsu (base, off, stdata, ctrl, mrdata, daddr, wdata, ldata, we);
  input [31:0] base;
  input [31:0] off;
  input [31:0] stdata;
  input [7:0] ctrl;
  input [31:0] mrdata;
  output [9:0] daddr;
  output [31:0] wdata;
  output [31:0] ldata;
  output we;
  wire [31:0] ea;
  ADD32 u_agu (.a(base), .b(off), .y(ea));
  ALN32 u_dab (.din(ea[11:2]), .sz(ctrl[5:4]), .dout(daddr));
  ALN32 u_algn (.din(mrdata), .sz(ctrl[5:4]), .dout(ldata));
  REG32 u_st (.d(stdata), .q(wdata), .en(ctrl[7]));
  BRU32 u_swe (.a(ea), .b(off), .op(ctrl[6:4]), .taken(we));
endmodule

module xbar (a0, a1, d0, d1, sel, maddr, mdata);
  input [9:0] a0;
  input [9:0] a1;
  input [31:0] d0;
  input [31:0] d1;
  input sel;
  output [9:0] maddr;
  output [31:0] mdata;
  MUX32 u_amux (.a(a0), .b(a1), .s(sel), .y(maddr));
  MUX32 u_dmux (.a(d0), .b(d1), .s(sel), .y(mdata));
endmodule

module core (instr, mrdata, iaddr, daddr, wdata, we, pc_out);
  input [31:0] instr;
  input [31:0] mrdata;
  output [9:0] iaddr;
  output [9:0] daddr;
  output [31:0] wdata;
  output we;
  output [31:0] pc_out;
  wire [7:0] ctrl;
  wire [31:0] imm;
  wire [31:0] ldata;
  wire [4:0] rd;
  wire [31:0] res;
  wire [4:0] rs1;
  wire [31:0] rs1v;
  wire [4:0] rs2;
  wire [31:0] rs2v;
  wire take;
  wire [31:0] wb;
  ifu u_ifu (.branch_pc(res), .take(take), .iaddr(iaddr), .pc_out(pc_out));
  idu u_idu (.instr(instr), .ctrl(ctrl), .imm(imm), .rs1(rs1), .rs2(rs2), .rd(rd));
  exu u_exu (.rs1v(rs1v), .rs2v(rs2v), .imm(imm), .ctrl(ctrl), .res(res), .take(take));
  lsu u_lsu (.base(rs1v), .off(imm), .stdata(rs2v), .ctrl(ctrl), .mrdata(mrdata), .daddr(daddr), .wdata(wdata), .ldata(ldata), .we(we));
  MUX32 u_wbsel (.a(res), .b(ldata), .s(ctrl[2]), .y(wb));
  RF32 u_rf (.ra1(rs1), .ra2(rs2), .wa(rd), .wd(wb), .we(ctrl[7]), .rd1(rs1v), .rd2(rs2v));
endmodule

module cluster (instr, mrd, iaddr, maddr, mdata, mwe, dbg);
  input [31:0] instr;
  input [31:0] mrd;
  output [9:0] iaddr;
  output [9:0] maddr;
  output [31:0] mdata;
  output mwe;
  output [31:0] dbg;
  wire [9:0] da0;
  wire [9:0] da1;
  wire [9:0] ia0;
  wire [9:0] ia1;
  wire [31:0] pc0;
  wire [31:0] pc1;
  wire [31:0] wd0;
  wire [31:0] wd1;
  wire we1;
  core u_c0 (.instr(instr), .mrdata(mrd), .iaddr(ia0), .daddr(da0), .wdata(wd0), .we(mwe), .pc_out(pc0));
  core u_c1 (.instr(instr), .mrdata(mrd), .iaddr(ia1), .daddr(da1), .wdata(wd1), .we(we1), .pc_out(pc1));
  xbar u_ixb (.a0(ia0), .a1(ia1), .d0(pc0), .d1(pc1), .sel(we1), .maddr(iaddr), .mdata(dbg));
  xbar u_dxb (.a0(da0), .a1(da1), .d0(wd0), .d1(wd1), .sel(we1), .maddr(maddr), .mdata(mdata));
endmodule

module soc (boot, dbg);
  input [31:0] boot;
  output [31:0] dbg;
  wire [9:0] iaddr;
  wire [31:0] instr;
  wire [9:0] maddr;
  wire [31:0] mdata;
  wire [31:0] mrd;
  wire mwe;
  cluster u_cl (.instr(instr), .mrd(mrd), .iaddr(iaddr), .maddr(maddr), .mdata(mdata), .mwe(mwe), .dbg(dbg));
  SRAM32 u_imem (.addr(iaddr), .wdata(boot), .we(mwe), .en(mwe), .rdata(instr));
  SRAM32 u_dmem (.addr(maddr), .wdata(mdata), .we(mwe), .en(mwe), .rdata(mrd));
endmodule
