#!/usr/bin/env bash
# Tier 1a of the LibreLane study (docs/internal/librelane_hier_flow.md §8
# step 7f): the TOP-SIDE handoff of arm H+B -- BUDA's bus corridors, in the
# file OpenROAD's `read_guides` reads (mechanism A).
#
#   flow/librelane/tier1a/guides.sh N
#
# Run it from anywhere, AFTER
#   (a) the blocks have hardened (n<N>/h/<cell>/runs/h/final/lef/<cell>.lef), and
#   (b) the top has run to just before detailed routing:
#         cd n<N>/h/top && librelane --dockerized --run-tag hb \
#             --to OpenROAD.DetailedRouting --skip OpenROAD.DetailedRouting config.json
#
# It writes n<N>/h/top/guides.buda and runs it, producing
# n<N>/h/top/out/buda_bus.guide.  `guide_route.tcl` (through phase 0's
# measure/run_or.sh) then puts those corridors into the ODB, and
# LibreLane's OWN DetailedRouting is resumed on it -- the README that
# harm.sh writes carries the three commands in order.
#
# WHY THE PLACED DEF AND NOT THE EMITTED ONE.  A guide is absolute
# top-level geometry, and the top LibreLane floorplans is NOT at the DEF's
# coordinates: `harm.py` translates every macro by one (dx, dy) so each
# halo lands inside the die (its docstring's PLACEMENT SHIFT).  Reading the
# run's own `*-odb-manualmacroplacement/` DEF makes the frame right by
# construction rather than by re-applying the shift here -- the phase-0
# recipe's rule (§8 step 5b), for the same reason.
#
# THE GCELL IS GIVEN, NOT READ.  OpenROAD defines the gcell grid at
# `global_route`, so a DEF written before it carries no `GCELLGRID`, and
# the manual-macro-placement DEF is pre-route by design.  6.9 um is
# sky130A's STEP as this flow's own runs write it (measured, §8 step 5b).
#
# THE LAYERS AND THE PATTERN are pins.sh's, and have to be: a corridor on
# a different track phase than the pins would put every bit's row between
# the pins the block was hardened with, and the router would pay the
# difference in jogs -- which is exactly what §8 step 5b measured with a
# hand template (22.7 % of the bus wire).  Any change to one file's stack
# belongs in the other.
set -euo pipefail
N=${1:?usage: guides.sh N   (after the blocks harden and the top reaches DetailedRouting)}; shift || true
if [ $# -ne 0 ]; then echo "guides.sh: unexpected arguments: $*" >&2; exit 1; fi
here=$(cd "$(dirname "$0")" && pwd); root=$(cd "$here/../../.." && pwd)
d="${T1A_DIR:-$here}/n$N"
top="$d/h/top"
[ -d "$top" ] || { echo "guides.sh: no $top -- run ./harm.sh $N --pins pins first" >&2; exit 1; }
: "${TAG:=hb}"
placed=$(ls -d "$top"/runs/"$TAG"/*-odb-manualmacroplacement/*.def 2>/dev/null | head -1 || true)
if [ -z "$placed" ]; then
    echo "guides.sh: no manual-macro-placement DEF under $top/runs/$TAG --" >&2
    echo "  run the top first: cd $top && librelane --dockerized --run-tag $TAG \\" >&2
    echo "      --to OpenROAD.DetailedRouting --skip OpenROAD.DetailedRouting config.json" >&2
    echo "  (or set TAG= to the run tag you used)" >&2
    exit 1
fi
: "${PDK_ROOT:=$HOME/.ciel}"
tech=$(ls "$PDK_ROOT"/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef 2>/dev/null || true)
[ -n "$tech" ] || { echo "guides.sh: no sky130A tech LEF under $PDK_ROOT -- set PDK_ROOT" >&2; exit 1; }

mkdir -p "$top/out"
/bin/cp -f "$placed" "$top/out/placed.def"
ln -sf "$tech" "$top/out/tech.tlef"
cells=$(sed -n 's/^MACRO \([A-Za-z_][A-Za-z0-9_]*\).*/\1/p' "$d/tpu.lef")
lefs=""
for c in $cells; do
    l="$d/h/$c/runs/h/final/lef/$c.lef"
    if [ ! -f "$l" ]; then
        echo "guides.sh: $c is not hardened ($l missing) -- see $d/h/README.md step 1" >&2
        exit 1
    fi
    ln -sf "$l" "$top/out/$c.lef"
    lefs="$lefs out/$c.lef"
done
# ONE LEF argument, so the hardened macros are concatenated into one file.
# `import_def_lef` takes exactly two paths; a per-cell import would need one
# command per cell and the last would win.
cat $(for c in $cells; do echo "$top/out/$c.lef"; done) > "$top/out/blocks.lef"

{
cat <<'HEAD'
# guides.buda -- generated by flow/librelane/tier1a/guides.sh; do not edit.
# Arm H+B's top-side handoff: route the array's buses in BUDA against the
# placement LibreLane actually used, and write the corridors OpenROAD's
# `read_guides` reads.  Every rule behind this file is in guides.sh.
require_file out/placed.def out/tech.tlef out/blocks.lef hint run flow/librelane/tier1a/guides.sh N, which stages these from the run

open_bdb :memory:
set_import_scale dbu
set_unit_check on
corner_margin dx 5000 dy 5000
set_min_stub_length 2000

def_layer 1 met1 H LOW 30
def_layer 2 met2 V LOW 30
def_layer 3 met3 H TOP 30
def_layer 4 met4 V TOP 30
def_layer 5 met5 H TOP 30
import_lef_tech out/tech.tlef
# The pattern pins.sh declares -- the pins and the corridors must be on one
# track phase or every bit pays a jog at the face.
def_track_pattern 2 160 SIGNAL 140 320 CUSTOM 140 320
def_track_pattern 3 190 SIGNAL 300 380 CUSTOM 300 380
set_bus_layers * met2,met3

# `allow_missing_footprints`: the DEF lists the top's own standard cells,
# which are in the PDK's cell LEF and not in the macros' -- at this stage
# they are UNPLACED (bbox -1) and the routing never sees them, so the LOUD
# fallback is the right one and its warnings are expected.
import_def_lef out/placed.def out/blocks.lef allow_missing_footprints

derive_busterms
add_blocks_from_bdb 0
run_hier_bundler
generate_hier_topologies
set_planner_param healersAhead 1
run_planner hier 5
run_nuts
check_design nuts
run_detailed_nuts
check_design dnuts
report_wirelength

# `terminal met2,met3`: the block pins pins.sh wrote are on that pair, and
# a guide has to reach them.  The gcell is given: see guides.sh.
emit_guides out/buda_bus.guide gcell 6.9 terminal met2,met3
emit_guides out/buda_guides.json
HEAD
} > "$top/guides.buda"

"$root/bin/buda" --no-viz "$top/guides.buda"
n=$(command grep -c '^(' "$top/out/buda_bus.guide" || true)
echo "tier1a: N=$N -> $top/out/buda_bus.guide  ($n guided net(s))"
echo "next: ../../../phase0/measure/run_or.sh $top/runs/$TAG $here/guide_route.tcl \\"
echo "        ODB=<the last .odb of that run> GUIDE=$top/out/buda_bus.guide OUT=$top/out"
