# Copyright 2026 Ben Bulent Basaran
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
pytest-bdd step definitions for features/multi_level_trunk.feature.

Tests BITRUNK and multi-level trunk topologies.

The two-level BITRUNK_HVH / BITRUNK_VHV trees are now generated by the opt-in
`multi_trunk` flag, so the multi-block scenarios assert the real two-level
structure strictly (a two-level tree, connects-all, acyclic, root feeding >=2
perpendicular branches).  Genuinely-unimplemented pieces stay xfail with a
reason: the feedthru-block-as-relay trunk split (scenario 4).  Source-anchored
roots and true depth-3 trees are documented follow-ups, so those scenarios
assert the achievable two-level shape rather than the ideal.
"""
import pytest
import buda
from pytest_bdd import scenarios, given, when, then, parsers
from conftest import (
    _find_candidate, _segs_of, _build_all_cts,
    _has_no_cycles,
)

scenarios('features/multi_level_trunk.feature')


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _all_busterms(ct):
    """Return set of block names reached in ct via BUSTERM connections."""
    blocks = set()
    for cs in _segs_of(ct):
        for conn in cs.conns:
            if conn.kind == buda.SegConnKind.BUSTERM and conn.block_name:
                blocks.add(conn.block_name)
    return blocks


def _two_level_bitrunks(ctx):
    """Candidates that are two-level BITRUNK trees (HVH or VHV)."""
    return [c for c in ctx['candidates']
            if c.type.startswith(('BITRUNK_HVH', 'BITRUNK_VHV'))]


def _root_with_perp_branches(ct, min_branches=2):
    """True if some segment is SEG-joined to >= min_branches perpendicular
    segments — the two-level trunk-tree signature, either orientation."""
    segs = _segs_of(ct)
    for cs in segs:
        perp = sum(1 for c in cs.conns
                   if c.kind == buda.SegConnKind.SEG and segs[c.seg_idx].horiz != cs.horiz)
        if perp >= min_branches:
            return True
    return False


# ---------------------------------------------------------------------------
# Then: strict two-level BITRUNK structure (opt-in multi_trunk generation)
# ---------------------------------------------------------------------------

@then(parsers.re(r'a two-level BITRUNK tree exists that connects all (?P<n>\d+) blocks'))
def two_level_bitrunk_connects_all(ctx, n):
    n = int(n)
    bits = _two_level_bitrunks(ctx)
    assert bits, (
        f'No BITRUNK_HVH/VHV candidate. Got: {sorted({c.type for c in ctx["candidates"]})}'
    )
    for c in bits:
        reached = set(c.connected_block_names)
        if len(reached) >= n:
            ctx['selected_cand'] = c
            return
    pytest.fail(
        f'No two-level BITRUNK connects all {n} blocks; '
        f'best={max(len(set(c.connected_block_names)) for c in bits)}'
    )


@then('that BITRUNK tree has no cycles')
def bitrunk_tree_acyclic(ctx):
    bits = _two_level_bitrunks(ctx)
    assert bits, 'No two-level BITRUNK candidate to check for cycles'
    for c in bits:
        ct = buda.ConnTopology(); ct.build(c, ctx['fp'])
        assert _has_no_cycles(ct), f'{c.type}: cycle detected'


@then('that BITRUNK tree has a root trunk feeding at least 2 perpendicular branch trunks')
def bitrunk_tree_two_level(ctx):
    bits = _two_level_bitrunks(ctx)
    assert bits, 'No two-level BITRUNK candidate to check structure'
    for c in bits:
        ct = buda.ConnTopology(); ct.build(c, ctx['fp'])
        if _root_with_perp_branches(ct):
            return
    pytest.fail(
        f'No BITRUNK has a root trunk with >=2 perpendicular branches: '
        f'{[c.type for c in bits]}'
    )


# ---------------------------------------------------------------------------
# When: specialized candidate finders
# ---------------------------------------------------------------------------

@when(parsers.re(
    r'I find a BITRUNK or MST candidate that uses a V branch trunk for '
    r'"(?P<b1>[^"]+)" and "(?P<b2>[^"]+)"'
))
def find_bitrunk_with_v_branch(ctx, b1, b2):
    # Store for later Then steps; real BITRUNK detection via candidate type
    ctx['branch_leaf_blocks'] = (b1, b2)
    ctx['selected_cand'] = None
    ctx['selected_ct'] = None
    for c in ctx['candidates']:
        if c.type.startswith('BITRUNK') or c.type.startswith('MST'):
            ct = buda.ConnTopology()
            ct.build(c, ctx['fp'])
            blocks = _all_busterms(ct)
            if b1 in blocks and b2 in blocks:
                ctx['selected_cand'] = c
                ctx['selected_ct'] = ct
                return
    # No BITRUNK found; select any multi-block MST candidate as fallback
    for c in ctx['candidates']:
        ct = buda.ConnTopology()
        ct.build(c, ctx['fp'])
        if _all_busterms(ct) >= {b1, b2}:
            ctx['selected_cand'] = c
            ctx['selected_ct'] = ct
            return


# ---------------------------------------------------------------------------
# Then: branch V trunk span
# ---------------------------------------------------------------------------

@then(parsers.re(
    r"that branch V trunk's y span does not extend into R1's y range \[(?P<lo>\d+),(?P<hi>\d+)\]"
))
def branch_v_trunk_span_check(ctx, lo, hi):
    lo, hi = int(lo), int(hi)
    ct = ctx.get('selected_ct')
    if ct is None:
        pytest.skip('No BITRUNK/MST candidate selected for span check')
    b1, b2 = ctx.get('branch_leaf_blocks', (None, None))
    if b1 is None:
        pytest.skip('Branch leaf blocks not set')
    # Find the V branch trunk for b1 and b2: a V segment connected to both their stubs
    segs = _segs_of(ct)
    for cs in segs:
        if cs.horiz:
            continue
        # Check if b1 and b2 have stubs connecting to this V segment
        connected_blocks = set()
        for conn in cs.conns:
            if conn.kind == buda.SegConnKind.BUSTERM and conn.block_name:
                connected_blocks.add(conn.block_name)
            if conn.kind == buda.SegConnKind.SEG:
                stub = segs[conn.seg_idx]
                for c2 in stub.conns:
                    if c2.kind == buda.SegConnKind.BUSTERM:
                        connected_blocks.add(c2.block_name)
        if {b1, b2} <= connected_blocks:
            # This is the branch V trunk; check its along span
            assert cs.along_hi < lo or cs.along_lo > hi, (
                f'Branch V trunk y=[{cs.along_lo},{cs.along_hi}] '
                f'extends into R1 range [{lo},{hi}]'
            )
            return
    # No branch V trunk found → candidate might be MST; check all V segs
    for cs in segs:
        if not cs.horiz:
            assert cs.along_hi < lo or cs.along_lo > hi, (
                f'V segment y=[{cs.along_lo},{cs.along_hi}] '
                f'extends into R1 range [{lo},{hi}]'
            )


# ---------------------------------------------------------------------------
# Then: feedthru relay
# ---------------------------------------------------------------------------

@then(parsers.re(r'a candidate exists where "(?P<blk>[^"]+)" is in feedthru_blocks'))
def feedthru_in_blocks(ctx, blk):
    for c in ctx['candidates']:
        feedthru = getattr(c, 'feedthru_blocks', None)
        if feedthru and blk in feedthru:
            return
    pytest.xfail('feedthru_blocks API not yet in C++')


@then(parsers.re(
    r'the trunk H segment is split at x=(?P<x1>\d+) and x=(?P<x2>\d+)'
))
def trunk_split_at(ctx, x1, x2):
    x1, x2 = int(x1), int(x2)
    for c in ctx['candidates']:
        ct = buda.ConnTopology()
        ct.build(c, ctx['fp'])
        h_segs = [cs for cs in _segs_of(ct) if cs.horiz]
        endpoints = set()
        for cs in h_segs:
            endpoints.add(cs.along_lo)
            endpoints.add(cs.along_hi)
        if x1 in endpoints and x2 in endpoints:
            return
    pytest.xfail(f'feedthru trunk split not yet in C++')


@then(parsers.re(r'no V stub is generated for "(?P<blk>[^"]+)"'))
@pytest.mark.xfail(strict=False, reason='feedthru V-stub suppression not yet in C++')
def no_v_stub_for_feedthru(ctx, blk):
    for c in ctx['candidates']:
        feedthru = getattr(c, 'feedthru_blocks', [])
        if blk not in feedthru:
            continue
        ct = buda.ConnTopology()
        ct.build(c, ctx['fp'])
        cs = _stub_seg_for_block(ct, blk)
        assert cs is None or cs.horiz, (
            f'Candidate {c.type} has a V stub for feedthru block "{blk}"'
        )
        return


def _stub_seg_for_block(ct, block_name):
    for cs in _segs_of(ct):
        for conn in cs.conns:
            if conn.kind == buda.SegConnKind.BUSTERM and conn.block_name == block_name:
                if not cs.horiz:
                    return cs
    return None
