# Copyright 2026 Ben Bulent Basaran
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""flow/tcl/array.tcl — the Tcl front end's own flow vehicle, end to end.

`test_tcl_front_end.py` pins the BRIDGE (framing, errors, encoding); this
pins the case the bridge exists for: a flow that COMPUTES its design — a
parameterized hierarchical array generated by Tcl loops — and drives the
whole hier pipeline through it, branching on `buda::query`.  The script is
self-checking (non-zero exit on a dirty result), so the assertion here is
mostly that its own verdict is CLEAN and that the structures the design
means to exercise actually formed.
"""
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_VEHICLE = _ROOT / "flow" / "tcl" / "array.tcl"

pytestmark = [pytest.mark.mid,
              pytest.mark.skipif(shutil.which("tclsh") is None,
                                 reason="no tclsh on this host")]


def _run(tmp_path, *args):
    r = subprocess.run(["tclsh", str(_VEHICLE), *map(str, args)],
                       capture_output=True, encoding="utf-8",
                       errors="replace", cwd=tmp_path, timeout=600)
    return r


def test_the_array_flow_ends_clean_and_forms_the_structures(tmp_path):
    # cwd=tmp_path on purpose: the vehicle resolves the repo from its own
    # path, so it must run from anywhere.
    r = _run(tmp_path)
    assert r.returncode == 0, r.stdout + r.stderr
    out = r.stdout
    assert "clean -- 0 overlaps, 0 unplaced, 0 audit violations" in out
    # The structures the generated design exists to exercise:
    # a cell-local TEMPLATE carrying every tile instance...
    assert "cell:tile_cell" in out
    assert "[t_0_0, t_0_1" in out, "no template instance list in the dump"
    # ...and the CONVERGENT cross-level fan-in merging the f_* buses.
    assert "FANIN:t_0_0/l_0_0" in out


def test_the_array_flow_scales_by_its_parameters(tmp_path):
    """The vehicle's point is that the design is COMPUTED: a different shape
    is two arguments, not a rewrite.  3 x 2 grows to 18 bundles.

    3 x 2 used to carry a shape-dependent RESIDUAL (2 x 2 was clean): the
    per-bit ANTENNA audit reported 8 units of dangling metal on bundle 10 —
    a `[t_1_0/l_0_1, t_0_1/l_1_0] -> t_1_1/l_0_0` fan-in routed TRUNK_H@y415
    whose trunk carries bits 0-7 while its M5 stub exists only for bits 4-7
    (the per-bit taper), so the trunk's metal ran on toward a junction its
    lower bits never make — the pair NUTS already warned about:

        [NUTS] junction infeasible: bundle 10 seg 0 cannot reach seg 1

    The cause was a BUSTERM TAP held out to every bit on its segment rather
    than to the bits whose own path terminates there, so bits 0-3 were
    stretched to a block they have no net at.  With the tap read per bit
    (Topology::seg_busterm_bits) the trunk retracts: bundle 10's detailed WL
    drops 1336 -> 944 and the design's 24977 -> 21615, and the ANTENNA audit
    — untouched by that change — stops reporting, which is what makes this a
    repaired vehicle rather than a silenced check.  The expectation is back
    to CLEAN, as the previous form of this test demanded it be.
    """
    r = _run(tmp_path, 3, 2)
    assert "3 x 2 tiles -> 18 bundles" in r.stdout
    assert r.returncode == 0, r.stdout + r.stderr
    assert "clean -- 0 overlaps, 0 unplaced, 0 audit violations" in r.stdout
    assert "dangling metal past its own attachments" not in r.stdout
