# Generated by tools/buda2tcl.py from flow/c_dd_detour.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/c_dd_detour.buda}
# C-double-double detour — one more detour level on top of flow/c_double_detour:
# instead of V stubs dropping straight from the H trunks into the blocks, TWO
# OOB V trunks run to the RIGHT of the blocks on the SAME grid line (x=500)
# with DISJOINT spans — one covering `up` and above, one covering `lo` and
# below — and short H stubs from each block's right face reach them:
#
#     +--------------------------------+   <- top H trunk (y=1700)
#     |                                |   <- right V trunk #1 (x=500,
#     |    [ up ]  --H stub-->---------+      span 1300..1700: up & above)
#     |
#     |    (vertically aligned pair)
#     |
#     |    [ lo ]  --H stub-->---------+   <- right V trunk #2 (x=500,
#     |                                |      span -300..100: lo & below)
#     +--------------------------------+   <- bottom H trunk (y=-300)
#     ^ V spine (x=-700)
#
# The H trunks now END at x=500, exactly on the right V trunks — the shared
# endpoints auto-connect (annotate_seg_conns records a junction wherever one
# segment's endpoint lands on a perpendicular segment; no edit_connect needed).
# The two right trunks share one Hanan line with disjoint spans — the same-line
# pattern from the four-block pin-span example, one level deeper.
#
# In the explorer the same shape is built interactively: Y at x=500, then
# `P` + click `up` + click the top H trunk (a perpendicular SEGMENT is an
# anchor — the span ends exactly on it), then `P` on the H trunk + one click
# on the new V trunk (a SINGLE anchor moves only the nearest end).

buda::def_layer {4} {M4} {H} {TOP} {44.44}
buda::def_layer {5} {M5} {V} {TOP} {50.00}

buda::add_block {lo} {0} {0} {400} {400}
buda::add_block {up} {0} {1000} {400} {1400}

buda::add_bus {w[4]} {lo.o} {up.i}
buda::run_bundler
buda::generate_topologies

# --- Build the double-double C by hand on bundle 1 --------------------------
buda::edit_topology {1} {new}
# seg 0/2: the outer H trunks now reach x=500 (the right V trunks' line)
buda::edit_add_trunk {H} {1700} {-700} {500}
# seg 1: the left V spine, as in the C-double detour
buda::edit_add_trunk {V} {-700} {-300} {1700}
buda::edit_add_trunk {H} {-300} {-700} {500}
# seg 3/4: the two right OOB V trunks — SAME line (x=500), DISJOINT spans.
# #1 spans `up` and above (to the top trunk), #2 spans `lo` and below.
buda::edit_add_trunk {V} {500} {1200} {1700}
buda::edit_add_trunk {V} {500} {-300} {200}
# seg 5/6: H stubs from each block's right face to its V trunk (the stub lands
# at the centre of the block∩trunk overlap: y=1300 for up, y=100 for lo)
buda::edit_add_stub {up} {3}
buda::edit_add_stub {lo} {4}
# Retract each right trunk's block-side end onto its stub (no dangle past the
# junction); the outer end stays on its H trunk.
buda::edit_set_span {3} {1300} {1700}
buda::edit_set_span {4} {-300} {100}
buda::edit_status
buda::edit_commit {pin}

# --- Concrete tracks so DetailedNUTS can place the 4 bits -------------------
buda::def_track_pattern {4} {-400} {POWER} {2} {1} {(SIGNAL} {2} {1)x5} {GROUND} {2} {1} {(SIGNAL} {2} {1)x5}
buda::def_track_pattern {5} {-500} {POWER} {3} {1} {(SIGNAL} {2} {1)x4} {GROUND} {3} {1} {(SIGNAL} {2} {1)x4}

buda::run_planner {5}
buda::run_nuts
buda::run_detailed_nuts
buda::check_design
buda::report_wl

corpus::end [info script]
