# Generated by tools/buda2tcl.py from flow/comprehensive_regression.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/comprehensive_regression.buda}
# ==========================================
# Comprehensive-flow REGRESSION fixture (frozen)
# ==========================================
# Frozen snapshot of demo/comprehensive_demo.buda as of the point its
# end-to-end counts were pinned by the tests below.  Kept SEPARATE from the
# live demo so demo/comprehensive_demo.buda is free to be tweaked for
# demonstrations without breaking these regression asserts.  Do not edit for
# demo purposes — edit the demo instead.
#
# Pinned by:
#   test/tests/test_flow_scripts.py::test_comprehensive_regression
#       5 hbundles, 26 NUTS segments, 153 detailed-NUTS bits, all clean
#   test/tests/test_planner_charge_pull_target.py::test_level2_junction_prediction_heals_demo_b3
#       bundle id 3 == the b3 keepout-strand (TRUNK_V+MST@x285 candidate)
# ==========================================

# 1. Define Layers (for channel routing only: M2=H, M3=V, over the blocks: M4=H, M5=V, long-haul trunks: M6=H M7=V)
buda::def_layer {2} {M2} {H} {LOW} {55.56}
buda::def_layer {3} {M3} {V} {LOW} {55.56}
buda::def_layer {4} {M4} {H} {TOP} {55.56}
buda::def_layer {5} {M5} {V} {TOP} {55.56}
buda::def_layer {6} {M6} {H} {TOP} {66.67}
buda::def_layer {7} {M7} {V} {TOP} {58.97}

# 2. Define Blocks & Connectivity

# --- Bundle 1: The Simple L-Topo ---
buda::add_block {u_cpu} {100} {100} {250} {250}
buda::add_block {u_mem} {750} {750} {900} {900}
buda::add_bus {b1[8]} {u_cpu.tx} {u_mem.rx}

# --- Bundle 2: A Trunk + 2 Stubs ---
buda::add_block {u_gpu} {100} {450} {250} {550}
buda::add_block {u_disp} {750} {500} {900} {600}
buda::add_block {u_noc_a} {400} {300} {500} {400}
buda::add_bus {b2[16]} {u_gpu.tx} {u_disp.rx,u_noc_a.rx}

# --- Bundle 3: A Trunk + 3 Stubs ---
buda::add_block {u_noc_b} {500} {650} {600} {750}
buda::add_block {u_io_src} {450} {50} {550} {150}
buda::add_block {u_io_dst} {450} {850} {550} {950}
buda::add_bus {b3[16]} {u_io_src.tx} {u_io_dst.rx,u_mem.rx}

# Nets can be bundled, too
buda::add_net {n1} {u_io_src.tx} {u_io_dst.rx,u_noc_b.rx,u_noc_a.rx,u_gpu.rx}
buda::add_net {n2} {u_io_src.tx} {u_io_dst.rx,u_noc_b.rx,u_noc_a.rx,u_gpu.rx}

# This stays alone
buda::add_net {n3} {u_io_src.tx} {u_io_dst.rx,u_noc_b.rx,u_noc_a.rx,u_gpu.rx,u_disp.rx}

# Wide obstacle between them forces a U-shape (except for M7 vertical)
# Try re-running after changing M5 with M7:
buda::add_keepout {320} {420} {700} {600} {M4} {M5} {M6}

# 3. Execution Flow
buda::run_bundler {strict}
buda::generate_topologies

# Declare the inter-bus track pitch BEFORE planning so the planner reserves its
# congestion bands at the same pitch that run_nuts will pack at.  Without this,
# the planner assumes the default pitch (1.0) while run_nuts below packs at 2.0,
# and run_nuts prints a "pitch differs from the pitch run_planner reserved for"
# warning (the band reservations would be too tight for the wider spacing).
buda::set_track_pitch {2.0}

# Run the planner (uses mock selection based on 'b2_'/'b3_' hints)
buda::run_planner {5}

# Non-Uniform Track Sharing: assign actual perpendicular track positions
# per layer so that no two buses with overlapping spans collide.
# Argument is the minimum spacing (track pitch) between placed buses; it matches
# the set_track_pitch above so the planner and NUTS agree (run_nuts with no arg
# would also reuse that pitch).
buda::run_nuts {2.0}

# Run the Detailed NUTS engine for placement of every bit on every segment on every bus/bundle and the vias:

# Track patterns are REQUIRED for Detailed NUTS
# Format: <layer_id> <origin> [<type> <width> <spacing>] ...
buda::def_track_pattern {2} {-100} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {3} {0} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {4} {-200} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {5} {0} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {6} {-400} {POWER} {3} {1} {(SIGNAL} {1} {1)x4} {GROUND} {3} {1} {(SIGNAL} {1} {1)x4}
buda::def_track_pattern {7} {-600} {POWER} {6} {2} {(SIGNAL} {2} {1)x4} {GROUND} {6} {1} {(SIGNAL} {2} {1)x4}

buda::run_detailed_nuts

corpus::end [info script]
