# Generated by tools/buda2tcl.py from flow/ndr_bond.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/ndr_bond.buda}
# NDR shield BONDING vehicle (R6, the `bond` token) — flat flow.
#
# A phase-1 shield is a wire on a reserved track carrying the rule's net
# NAME and nothing tying it to that net: labeled metal, not grid metal
# (docs/internal/opens_ndr.md §1).  `bond` closes that: after placement
# every EMITTED shield is strapped to the power grid with a via wherever an
# identity-matching rail crosses it on an adjacent PERPENDICULAR layer.
#
#   gndbus  width x1.5 shield bus net GND bond
#           -> flanking shields, each strapped where the GND rails of the
#              neighbouring layers cross it (label equality).
#   vssbit  width x2   shield bit net VSS bond stride 3
#           -> a shield in EVERY gap, each strapped to the same GND rails
#              through the SUPPLY-FAMILY predicate (VSS and GND are one
#              ground net for shielding — ndr_shield_net_matches), and
#              STRIDED: one strap every 3rd crossing instead of all of
#              them.  Both extremes are anchored regardless, so no tail
#              hangs unbonded off the last strap.
#
# Both layer pairs alternate H/V, so every shield has crossing rails: the
# NDR_BOND audit (an emitted shield with zero straps) must stay silent and
# check_design must end clean.  The strap count is reported by
# run_detailed_nuts — the two rules together show the cost of the choice,
# since gndbus straps every crossing and vssbit every third.

buda::add_block {blkA} {0} {0} {200} {300}
buda::add_block {blkB} {800} {0} {1000} {300}
buda::add_block {blkC} {0} {400} {200} {700}
buda::add_block {blkD} {800} {400} {1000} {700}

buda::add_bus {gnd_[4]} {blkA.p} {blkB.q}
buda::add_bus {vss_[4]} {blkC.p} {blkD.q}

buda::def_layer {3} {M3} {H} {20}
buda::def_layer {4} {M4} {V} {20}
buda::def_layer {5} {M5} {H} {TOP} {20}
buda::def_layer {6} {M6} {V} {TOP} {20}

buda::def_ndr {gndbus} {width} {x1.5} {shield} {bus} {net} {GND} {bond}
buda::def_ndr {vssbit} {width} {x2} {shield} {bit} {net} {VSS} {bond} {stride} {3}
buda::set_ndr {gnd_} {gndbus}
buda::set_ndr {vss_} {vssbit}

buda::run_bundler {STRICT} {--dump}
buda::dump_ndr

buda::generate_topologies
buda::set_track_pitch {3}
buda::run_planner {1}

# One GND rail per period on every layer — the bonding target.  12 SIGNAL
# slots between the rails leave room for both runs (gndbus 4 bits = 11
# slots, vssbit 4 bits = 13).
buda::def_track_pattern {3} {0} {VDD} {2} {1} {(_} {1} {1)x12} {GND} {2} {1}
buda::def_track_pattern {4} {0} {VDD} {2} {1} {(_} {1} {1)x12} {GND} {2} {1}
buda::def_track_pattern {5} {0} {VDD} {2} {1} {(_} {1} {1)x12} {GND} {2} {1}
buda::def_track_pattern {6} {0} {VDD} {2} {1} {(_} {1} {1)x12} {GND} {2} {1}

buda::run_nuts
buda::run_detailed_nuts
buda::dump_ndr
buda::check_design
buda::report_wirelength

corpus::end [info script]
