# Generated by tools/buda2tcl.py from flow/teg_over_audit.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/teg_over_audit.buda}
# TEG-over end-to-end QoR vehicle (teg_multirect_status.md open 2).
#
# The §1.1 geometry as a full-pipeline flow: pin the candidate that FORMERLY
# relied on a TEG bridge (TRUNK_V@x250 — the V trunk sits in the notch and
# crosses the base only, so the tall arm needs explicit connection metal),
# route it through planner -> NUTS -> DetailedNUTS, and audit.
#
# HISTORY: this flow merged EXPECTED DIRTY — bridges were generation-only, so
# the route was built without its bridge and check_design reported TEG_OPEN
# (the open 1(b) audit, PR #821), corpus row 1 viol.  Open 1(a) then landed:
# the trunk generator emits a real perpendicular connector leg to each
# un-spanned rect (ordinary segments; Topology::bridge_segments is
# legacy-load only), so this flow now runs EXPECTED CLEAN — 3 segments
# (trunk + stub + leg), 12 bit-wires, both audits Success — and the corpus
# row guards emission's health: if the leg regresses, TEG_OPEN fires and the
# row moves LOUDLY.
#
# Candidate pin: `select_topology 1 10` is a hard 1-based index —
# TRUNK_V@x250 in the WL-sorted post-emission pool (18 candidates, none
# bridged; the leg's real WL re-sorted the pool, which is why the pre-
# emission pin was 13).  A hard index is fragile by nature, but there is no
# pin-by-type selector; the guards are:
#   * an index past the pool is a hard error (the flow exits non-zero), and
#   * test_flow_scripts.py::test_teg_over_audit_flow_routes_clean asserts
#     the planner line shows `TRUNK_V@x250 [pinned]` AND both check_design
#     Success lines — so a re-sorted pool that lands a different shape on
#     index 10 fails the test loudly instead of silently auditing a
#     different candidate.
#
# Geometry (shared with test/tests/test_teg_open.py):
#   L block: tall arm (0,0)-(100,400) + wide base (0,0)-(400,100), OVER
#   src:     (500,150)-(600,250)

buda::add_block {src} {500} {150} {600} {250}
buda::add_block {L} {rect} {0} {0} {100} {400} {rect} {0} {0} {400} {100} {teg_mode} {over}

buda::def_layer {4} {M4} {H} {TOP} {0}
buda::def_layer {5} {M5} {V} {TOP} {0}

buda::add_bus {d[4]} {src.tx} {L.rx}

buda::run_bundler {STRICT}
buda::generate_topologies

buda::def_track_pattern {4} {0} {(SIGNAL} {2} {2)x8}
buda::def_track_pattern {5} {0} {(SIGNAL} {2} {2)x8}

# The formerly-bridge-reliant candidate (see header): TRUNK_V@x250 + leg.
buda::select_topology {1} {10}

buda::run_planner
buda::run_nuts
buda::check_design
buda::run_detailed_nuts
buda::check_design
buda::report_wl

corpus::end [info script]
