# Generated by tools/buda2tcl.py from flow/teg_mst_over.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/teg_mst_over.buda}
# MST-on-TEG-over end-to-end vehicle (teg_multirect_status.md Final-state
# limitation 1, RESOLVED 2026-08-25).
#
# An MST edge connects each block pair at the closest rect pair, so a
# `teg_mode over` receiver's OTHER rects used to go entirely unreached — the
# firing repro this flow is adapted from pinned TEG_OPEN at both placed
# stages naming rect#1 of r2.  `add_mst_teg_attachments` now runs on the
# FINISHED tree (after complete_relay_junctions) and attaches every rect the
# tree leaves unreached with real metal, so this flow runs EXPECTED CLEAN.
#
# Two bundles pin the fix AND its control on one design:
#   bundle 1 (bus d, no r4): the r1→r2 edge lands on r2's near rect only, so
#     the attachment pass emits a T-stub from rect#1's face onto the tree —
#     the limitation-1 fix's proof;
#   bundle 2 (bus e, + r4):  the r2→r4 edge SPANS rect#1 — pass-through
#     contact IS attachment — so the pass must add NOTHING (the control that
#     must not change: no redundant metal on an already-reached rect).
#
# Both are pinned by TYPE (MST_HV — the selector that survives a re-sorted
# pool); the flow-script guard is
# test_flow_scripts.py::test_teg_mst_over_flow_routes_clean, which asserts
# both pins and both check_design Success lines.
#
# Geometry (shared with test/tests/test_teg_open.py's MST tests):
#   r2: two disjoint rects (500,0)-(600,100) + (900,0)-(1000,100), OVER

buda::add_block {src} {0} {0} {100} {100}
buda::add_block {r1} {300} {300} {400} {400}
buda::add_block {r2} {rect} {500} {0} {600} {100} {rect} {900} {0} {1000} {100} {teg_mode} {over}
buda::add_block {r3} {300} {600} {400} {700}
buda::add_block {r4} {1200} {0} {1300} {100}

buda::def_layer {4} {M4} {H} {TOP} {0}
buda::def_layer {5} {M5} {V} {TOP} {0}

buda::add_bus {d[4]} {src.tx} {r1.a,r2.b,r3.c}
buda::add_bus {e[4]} {src.ty} {r1.d,r2.e,r3.f,r4.g}

buda::run_bundler {STRICT}
buda::generate_topologies

buda::def_track_pattern {4} {0} {(SIGNAL} {2} {2)x8}
buda::def_track_pattern {5} {0} {(SIGNAL} {2} {2)x8}

# The MST tree on the OVER receiver: bundle 1 needs the attachment stub,
# bundle 2 (the spanning control) must route with no extra metal.
buda::select_topology {1} {MST_HV}
buda::select_topology {2} {MST_HV}

buda::run_planner
buda::run_nuts
buda::check_design
buda::run_detailed_nuts
buda::check_design
buda::report_wl
buda::visualize

corpus::end [info script]
