#!/usr/bin/env python3
"""
generate_large_demo.py — produces the large-scale stress-test demos.

Two demo vehicles are generated from the same SoC floorplan (14 functional
blocks, ~10400 × 10200 units, three metal layers with 10% overhead each):

  1. FLAT  — ``large_scale_demo.buda`` / ``large_scale_demo_buses.buda``
     Top-level-only floorplan. Every bus connects two top blocks with a
     2-part pin (``u_cpu0.c0l3d0_tx``); the CLI's ``_pin_instance`` splits at
     the LAST dot, so the endpoint resolves to the top block ``u_cpu0``.
     The STRICT bundler collapses ports that share a src+dst block pair, so
     the flat demo has fewer, fatter bundles.  This file is hand-maintained
     (bus widths were tuned for speed); ``generate()`` reproduces its shape
     but is not run against the checked-in copy by default — see __main__.

  2. PSEUDO-HIER — ``large_scale_demo_pseudo_hier.buda``
     "Fakes" a hierarchy by overlaying leaf sub-blocks inside each top block:
     each top block becomes a transparent ``container`` envelope, and every
     bus port gets its own tiled leaf sub-block ``<parent>.<tag>``.  Buses use
     3-part pins (``u_cpu0.c0l3d0.tx``) so ``_pin_instance`` resolves the
     endpoint to the sub-block ``u_cpu0.c0l3d0`` — giving each port its own
     bundle and routing to a distinct point inside the envelope, the way a
     real hier flow would.  Generated by transforming the flat buses file, so
     it stays bus-for-bus identical to the flat demo (same widths, same count),
     differing only in hierarchy.

Layer assignments (from topology.cpp):
  M4 (layer 4, H) — horizontal stubs in L/Z/U shapes
  M5 (layer 5, V) — all vertical segments
  M6 (layer 6, H) — horizontal trunks in U_VHV shapes (long-haul detours)
"""

import math
import os
import re

# ---------------------------------------------------------------------------
# Floorplan blocks  (name, x1, y1, x2, y2)
# ---------------------------------------------------------------------------
BLOCKS = [
    # Compute column (left)
    ("u_cpu0",   200,   200,  1000,  1600),   # CPU core cluster 0
    ("u_cpu1",   200,  2000,  1000,  3400),   # CPU core cluster 1
    ("u_gpu",    200,  3800,  2000,  6600),   # GPU cluster
    ("u_npu",    200,  7000,  2000,  8400),   # Neural processing unit

    # Cache / fabric (centre)
    ("u_l3",    2400,   200,  6000,  3400),   # Shared L3 cache (large)
    ("u_noc",   2400,  3800,  8400,  6600),   # Network-on-chip fabric

    # Memory (right)
    ("u_hbm0",  8800,   200, 10400,  3400),   # HBM controller 0
    ("u_hbm1",  8800,  3800, 10400,  6600),   # HBM controller 1
    ("u_ddr",   8800,  7000, 10400,  8400),   # DDR controller

    # Peripherals (bottom row)
    ("u_disp",  2400,  7000,  5000,  8400),   # Display controller
    ("u_isp",   5600,  7000,  8400,  8400),   # Image signal processor
    ("u_pcie",  2400,  9000,  5000, 10200),   # PCIe subsystem
    ("u_usb",   5600,  9000,  8400, 10200),   # USB / IO hub
    ("u_sec",   8800,  9000, 10400, 10200),   # Security / crypto
]

# ---------------------------------------------------------------------------
# Port groups  (prefix, src_block, dst_block, width_bits, num_ports)
#
# Each port in a group becomes one BUDA bundle; ports are separated by using
# hierarchical driver/receiver pin names  (u_block.prefix_portN.tx / .rx)
# so the STRICT bundler assigns each port its own bundle.
# ---------------------------------------------------------------------------
PORT_GROUPS = [
    # ── CPU0 ↔ L3 cache ───────────────────────────────────────────────────
    ("c0l3d", "u_cpu0", "u_l3",   128, 2),   # 2× 128-bit data
    ("c0l3t", "u_cpu0", "u_l3",    64, 1),   # 64-bit tag
    ("c0l3c", "u_cpu0", "u_l3",    32, 1),   # 32-bit ctrl

    # ── CPU1 ↔ L3 cache ───────────────────────────────────────────────────
    ("c1l3d", "u_cpu1", "u_l3",   128, 2),
    ("c1l3t", "u_cpu1", "u_l3",    64, 1),
    ("c1l3c", "u_cpu1", "u_l3",    32, 1),

    # ── CPU0 → NoC ────────────────────────────────────────────────────────
    ("c0ncp", "u_cpu0", "u_noc",   64, 4),   # 4× 64-bit NoC ports
    ("c0ncm", "u_cpu0", "u_noc",   32, 2),   # 2× 32-bit mgmt

    # ── CPU1 → NoC ────────────────────────────────────────────────────────
    ("c1ncp", "u_cpu1", "u_noc",   64, 4),
    ("c1ncm", "u_cpu1", "u_noc",   32, 2),

    # ── GPU → NoC ─────────────────────────────────────────────────────────
    ("gpncp", "u_gpu",  "u_noc",  128, 6),   # 6× 128-bit data ports
    ("gpncc", "u_gpu",  "u_noc",   32, 2),   # 2× 32-bit ctrl

    # ── GPU → L3 ──────────────────────────────────────────────────────────
    ("gpl3p", "u_gpu",  "u_l3",   128, 4),

    # ── NPU → NoC ─────────────────────────────────────────────────────────
    ("npncp", "u_npu",  "u_noc",   64, 4),
    ("npncc", "u_npu",  "u_noc",   32, 2),

    # ── NPU → L3 ──────────────────────────────────────────────────────────
    ("npl3p", "u_npu",  "u_l3",    64, 2),

    # ── L3 → NoC ──────────────────────────────────────────────────────────
    ("l3ncp", "u_l3",   "u_noc",  128, 8),   # 8× 128-bit (deliberate congestion)
    ("l3ncc", "u_l3",   "u_noc",   32, 2),

    # ── NoC → HBM0 ────────────────────────────────────────────────────────
    ("nh0_p", "u_noc",  "u_hbm0", 128, 4),

    # ── NoC → HBM1 ────────────────────────────────────────────────────────
    ("nh1_p", "u_noc",  "u_hbm1", 128, 4),

    # ── NoC → DDR ─────────────────────────────────────────────────────────
    ("ndr_p", "u_noc",  "u_ddr",   64, 4),

    # ── NoC → Display ─────────────────────────────────────────────────────
    ("ndsp_", "u_noc",  "u_disp", 128, 4),
    ("ndsc_", "u_noc",  "u_disp",  32, 2),

    # ── NoC → ISP ─────────────────────────────────────────────────────────
    ("nisp_", "u_noc",  "u_isp",   64, 4),

    # ── NoC → PCIe ────────────────────────────────────────────────────────
    ("npc__", "u_noc",  "u_pcie",  32, 6),

    # ── NoC → USB ─────────────────────────────────────────────────────────
    ("nusb_", "u_noc",  "u_usb",   16, 4),

    # ── NoC → Security ────────────────────────────────────────────────────
    ("nsec_", "u_noc",  "u_sec",   32, 4),

    # ── Security → CPUs ───────────────────────────────────────────────────
    ("sc0_p", "u_sec",  "u_cpu0",  64, 2),
    ("sc1_p", "u_sec",  "u_cpu1",  64, 2),

    # ── ISP → NoC (return data path) ──────────────────────────────────────
    ("isn_p", "u_isp",  "u_noc",   32, 4),

    # ── GPU → Display (direct framebuffer bypass) ──────────────────────────
    ("gdsp_", "u_gpu",  "u_disp", 128, 4),

    # ── PCIe → NoC (return) ───────────────────────────────────────────────
    ("pcn_p", "u_pcie", "u_noc",   32, 4),

    # ── 8-bit management buses ────────────────────────────────────────────
    ("c0sm_", "u_cpu0", "u_sec",    8, 2),
    ("c1sm_", "u_cpu1", "u_sec",    8, 2),
    ("c0pm_", "u_cpu0", "u_pcie",   8, 1),
    ("c0um_", "u_cpu0", "u_usb",    8, 1),
]


def generate(out_path: str) -> None:
    lines: list[str] = []

    def w(*args):
        lines.append(" ".join(str(a) for a in args))

    def blank():
        lines.append("")

    def comment(text):
        lines.append(f"# {text}")

    # ------------------------------------------------------------------
    comment("=" * 66)
    comment("BUDA Large-Scale Stress-Test Demo — FLAT variant")
    comment("14 top blocks · 4–64-bit buses · M4/M5/M6 layers")
    comment("2-part pins → STRICT bundler collapses ports by src+dst block pair")
    comment("=" * 66)
    blank()

    # Layers
    comment("Layers: M4 horizontal, M5 vertical, M6 long-haul horizontal")
    w("def_layer", 4, "M4", "H", "TOP", "10.0")
    w("def_layer", 5, "M5", "V", "TOP", "10.0")
    w("def_layer", 6, "M6", "H", "TOP", "10.0")
    blank()

    # Blocks
    comment("Floorplan blocks")
    for name, x1, y1, x2, y2 in BLOCKS:
        w("add_block", name, x1, y1, x2, y2)
    blank()

    # Buses — one add_bus line per bundle (vector syntax)
    comment("Buses (vector syntax: add_bus prefix[N] drv rcv)")
    bundle_list = []   # (hint, src_block, dst_block) for topology generation
    for pfx, src, dst, width, num_ports in PORT_GROUPS:
        src_inst = src
        dst_inst = dst
        for port in range(num_ports):
            pin_tag  = f"{pfx}{port}"
            # 2-part pins: _pin_instance splits at the LAST dot, so the
            # endpoint resolves to the top block (flat flow).
            drv_pin  = f"{src_inst}.{pin_tag}_tx"
            rcv_pin  = f"{dst_inst}.{pin_tag}_rx"
            w("add_bus", f"{pin_tag}[{width}]", drv_pin, rcv_pin)
            bundle_list.append((f"{pin_tag}_", src, dst))
        blank()

    # Bundler
    comment("Stage 1 — bundle nets by driver+receiver instance")
    w("run_bundler", "strict")
    blank()

    # Topology generation — one call per bundle
    comment("Stage 2 — generate L/Z/U topology candidates per bundle")
    for hint, src, dst in bundle_list:
        w("generate_topologies_for_bundle", hint, src, dst)
    blank()

    # Planner
    comment("Stage 3 — congestion-aware topology selection (fattest-bus-first)")
    w("run_planner", 1)
    blank()

    # NUTS
    comment("Stage 4 — NUTS abstract track placement (pitch=2.0)")
    w("run_nuts", "2.0")
    blank()

    comment("Visualize")
    w("visualize")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    # Summary
    total_bundles = sum(n for _, _, _, _, n in PORT_GROUPS)
    total_nets    = sum(w * n for _, _, _, w, n in PORT_GROUPS)
    print(f"Written: {out_path}")
    print(f"  Blocks  : {len(BLOCKS)}")
    print(f"  Bundles : {total_bundles}")
    print(f"  Nets    : {total_nets}")


# ---------------------------------------------------------------------------
# Pseudo-hier generation
#
# Transforms the (flat, 2-part) buses file into a hierarchy-faking demo:
#   * each top block → transparent `container` envelope
#   * every bus port → a tiled leaf sub-block `<parent>.<tag>` inside its
#     parent envelope
#   * every bus → 3-part pins so the endpoint resolves to the sub-block
# The buses file is the single source of widths/counts, so the pseudo-hier
# demo stays bus-for-bus identical to the flat demo.
# ---------------------------------------------------------------------------
_BUS_RE = re.compile(
    r"^\s*add_bus\s+(\w+)\[(\d+)\]\s+(\S+)\s+(\S+)\s*$"
)


def _parse_flat_buses(buses_path: str):
    """Yield (tag, width, src_block, dst_block) for each add_bus line."""
    out = []
    with open(buses_path) as f:
        for line in f:
            m = _BUS_RE.match(line)
            if not m:
                continue
            tag, width, drv, rcv = m.group(1), int(m.group(2)), m.group(3), m.group(4)
            # 2-part flat pin: "<block>.<tag>_tx" — block is everything
            # before the first dot.
            src = drv.split(".", 1)[0]
            dst = rcv.split(".", 1)[0]
            out.append((tag, width, src, dst))
    return out


def _best_grid(n, w, h):
    """Choose (cols, rows) covering n cells that maximizes the smaller cell
    dimension for an envelope of `w`×`h` — so a wide bus fits its face
    regardless of which way it approaches."""
    best = None
    for cols in range(1, n + 1):
        rows = int(math.ceil(n / cols))
        cell_min = min(w / cols, h / rows)
        if best is None or cell_min > best[0]:
            best = (cell_min, cols, rows)
    return best[1], best[2]


def _tile_subblocks(x1, y1, x2, y2, tags, margin_frac=0.04, gap_frac=0.12):
    """Grid-tile leaf sub-blocks for `tags` inside a parent bbox.

    Returns {tag: (sx1, sy1, sx2, sy2)}. Sub-blocks are inset from the
    envelope edges and separated by a small gap so they remain distinct leaf
    cells; the grid is aspect-aware so each cell stays as square (and thus as
    large in its smaller dimension) as the port count allows — otherwise a
    crowded/narrow envelope produces faces too thin to host a wide bus.
    """
    n = len(tags)
    if n == 0:
        return {}
    mx = (x2 - x1) * margin_frac
    my = (y2 - y1) * margin_frac
    ix1, iy1, ix2, iy2 = x1 + mx, y1 + my, x2 - mx, y2 - my
    cols, rows = _best_grid(n, ix2 - ix1, iy2 - iy1)
    cell_w = (ix2 - ix1) / cols
    cell_h = (iy2 - iy1) / rows
    gx = cell_w * gap_frac
    gy = cell_h * gap_frac
    placement = {}
    for i, tag in enumerate(sorted(tags)):
        r = i // cols
        c = i % cols
        sx1 = ix1 + c * cell_w + gx / 2
        sy1 = iy1 + r * cell_h + gy / 2
        sx2 = ix1 + (c + 1) * cell_w - gx / 2
        sy2 = iy1 + (r + 1) * cell_h - gy / 2
        placement[tag] = (round(sx1), round(sy1), round(sx2), round(sy2))
    return placement


# Per-port bus width is capped in the pseudo-hier variant: each port lands on
# its own small leaf sub-block, and a sub-block face can only host so many
# signal tracks. A full-width (e.g. 64-bit) landing site would need ~1000+
# units of face — far more than fits when a dozen ports share one envelope.
# Real hierarchy avoids this with shared busterms; the pseudo-hier demo instead
# narrows each per-port bus so it lands cleanly. The hierarchy-faking value is
# in the per-port bundling + interior routing, not the raw bit count.
PSEUDO_MAX_WIDTH = 8


def generate_pseudo_hier(out_path: str, buses_path: str,
                         max_width: int = PSEUDO_MAX_WIDTH) -> None:
    lines: list[str] = []

    def w(*args):
        lines.append(" ".join(str(a) for a in args))

    def blank():
        lines.append("")

    def comment(text):
        lines.append(f"# {text}")

    buses = [(tag, min(width, max_width), src, dst)
             for tag, width, src, dst in _parse_flat_buses(buses_path)]

    # Collect the tags each top block hosts (as src or dst endpoint).
    tags_by_block: dict[str, set] = {name: set() for name, *_ in BLOCKS}
    for tag, _width, src, dst in buses:
        tags_by_block.setdefault(src, set()).add(tag)
        tags_by_block.setdefault(dst, set()).add(tag)

    # ------------------------------------------------------------------
    comment("=" * 66)
    comment("BUDA Large-Scale Stress-Test Demo — PSEUDO-HIER variant")
    comment(f"14 container blocks · {len(buses)} bundles · tiled leaf sub-blocks")
    comment("Fakes a hierarchy: each top block is a transparent `container`")
    comment("envelope; every bus port gets its own leaf sub-block so 3-part")
    comment("pins route to a distinct point inside the envelope (per-port")
    comment("bundling), the way a real hier flow would.")
    comment(f"Per-port bus width capped at {max_width} bits so each narrow")
    comment("leaf landing site is routable (real hier uses shared busterms).")
    comment("=" * 66)
    blank()

    comment("Layers: M4 horizontal, M5 vertical, M6 long-haul horizontal")
    w("source", "../flow/tracks/tracks.buda")
    blank()

    # Container envelopes + tiled leaf sub-blocks.
    comment("Top blocks as transparent container envelopes")
    sub_bboxes: dict[str, dict] = {}
    for name, x1, y1, x2, y2 in BLOCKS:
        w("add_block", name, x1, y1, x2, y2, "container")
        sub_bboxes[name] = _tile_subblocks(x1, y1, x2, y2, tags_by_block.get(name, set()))
    blank()

    comment("Leaf sub-blocks (one per bus port, tiled inside its envelope)")
    for name, *_ in BLOCKS:
        placement = sub_bboxes[name]
        for tag in sorted(placement):
            sx1, sy1, sx2, sy2 = placement[tag]
            w("add_block", f"{name}.{tag}", sx1, sy1, sx2, sy2)
    blank()

    # Buses — 3-part pins resolve the endpoint to the leaf sub-block.
    comment("Buses (3-part pins → endpoint resolves to leaf sub-block)")
    for tag, width, src, dst in buses:
        drv_pin = f"{src}.{tag}.tx"
        rcv_pin = f"{dst}.{tag}.rx"
        w("add_bus", f"{tag}[{width}]", drv_pin, rcv_pin)
    blank()

    comment("Stage 1 — bundle nets by driver+receiver instance (per-port)")
    w("run_bundler", "strict")
    blank()

    comment("Stage 2 — generate L/Z/U topology candidates (src/dst auto-derived)")
    w("generate_topologies")
    blank()

    comment("Stage 3 — congestion-aware topology selection")
    w("run_planner", 5)
    blank()

    comment("Stage 4 — NUTS abstract track placement")
    w("run_nuts")
    blank()

    comment("Stage 9 — detailed per-bit track placement")
    w("run_detailed_nuts")
    blank()

    comment("Visualize")
    w("visualize")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    n_sub = sum(len(v) for v in sub_bboxes.values())
    print(f"Written: {out_path}")
    print(f"  Container blocks : {len(BLOCKS)}")
    print(f"  Leaf sub-blocks  : {n_sub}")
    print(f"  Bundles          : {len(buses)}")


if __name__ == "__main__":
    here = os.path.dirname(__file__)
    buses = os.path.join(here, os.pardir, "flow", "large_scale_demo_buses.buda")

    # The flat demo (large_scale_demo.buda + its buses file) is hand-maintained
    # for speed; generate_pseudo_hier() derives the pseudo-hier variant from the
    # flat buses so the two stay in sync. Only the pseudo-hier file is emitted
    # here to avoid clobbering the tuned flat copies.
    generate_pseudo_hier(
        os.path.join(here, "large_scale_demo_pseudo_hier.buda"), buses
    )
