# Generated by tools/buda2tcl.py from flow/big_data_test/big2/b1_bus_007.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big2/b1_bus_007.buda}
# issue: mst topos miss abutted blocks

source [file join $::corpus::root {big_data_test/big2/tracks4top.tcl}]
buda::add_block {blk_00} {1250} {3780} {2230} {4775}
buda::add_block {blk_05} {1250} {3225} {2230} {3780}
buda::add_block {blk_06} {0} {4630} {1250} {5170}
buda::add_block {blk_17} {2880} {5350} {4280} {6300}
buda::add_block {blk_21} {3500} {3100} {4870} {3645}
buda::add_block {blk_33} {3500} {3645} {4220} {4615}
buda::add_bus {bus_007[28]} {blk_00.p} {blk_06.p,blk_33.p,blk_17.p,blk_05.p,blk_21.p}
buda::run_bundler
buda::generate_topologies
buda::check_design {topo} {all}
buda::run_planner
buda::run_nuts
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design
buda::visualize

corpus::end [info script]
