# Generated by tools/buda2tcl.py from flow/big_data_test/big2/b24_bus_056.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big2/b24_bus_056.buda}
# From big2_b4_b24.buda
source [file join $::corpus::root {big_data_test/big2/tracks4top.tcl}]

buda::set_die {6100} {6300}
buda::add_block {blk_09} {3500} {2570} {4870} {3100}
buda::add_block {blk_14} {2230} {2720} {3500} {3365}
buda::add_block {blk_19} {0} {2660} {1250} {3310}
buda::add_block {blk_39} {4870} {3365} {6100} {4425}

# --- bundle 24 (bus_056)
buda::add_bus {bus_056[48]} {blk_09.p} {blk_14.p,blk_39.p,blk_19.p}

buda::run_bundler
buda::generate_topologies

# Pin the exact topologies that were buggy in the full big2.buda run, now fixed:
#   bundle (b24)=TRUNK_V@x5485 (topo 8) — generation used to leave blk_09 uncovered
#                                            (fixed: coverage-safe stub suppression).
# The TRUNK_V candidate index moved (4->8) once blk_09's stub is no longer dropped.
# (index 10 since the hanan_loci default flip grew the pool 22->26; same
#  pinned candidate by topo_uid: TRUNK_V+MST@x2865 wl=5240)
buda::select_topology {1} {10}
# Check the SELECTED topologies before planning so a topology-gen coverage gap
# (bundle 24 / blk_09) is caught at the topo stage and can't be masked by a later
# NUTS/DNUTS change. Bundle 4's detach is a NUTS-stage artifact (clean at topo).
buda::check_design {topo}
buda::dump_topologies {--conn}
buda::run_planner
buda::dump_topologies {--conn}
buda::run_nuts
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design
buda::visualize
corpus::finish [info script] {0}
