# Generated by tools/buda2tcl.py from flow/big_data_test/big2/b34_bus_028.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big2/b34_bus_028.buda}
# three abuted blocks. Trunk contained in its passthru block.
# we should not force it to connect to a block edge, but ensure that it doesn't slide out.
# how to do it?

# source tc3b_flat_x5.buda
buda::add_block {blk_00} {1250} {3780} {2230} {4775}
buda::add_block {blk_15} {2230} {3365} {3500} {4615}
buda::add_block {blk_32} {2230} {4615} {3500} {5350}
buda::add_bus {bus_028[28]} {blk_15.p} {blk_32.p,blk_00.p}

buda::run_bundler
buda::generate_topologies
buda::select_topology {1} {2}
buda::dump_topologies {--conn}
source [file join $::corpus::root {big_data_test/big2/tracks4top.tcl}]
buda::run_planner
buda::run_nuts
buda::run_detailed_nuts
buda::check_design
#visualize

corpus::end [info script]
