# Generated by tools/buda2tcl.py from flow/big_data_test/big2/b3_bus_023.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big2/b3_bus_023.buda}
# issue: no mst, nor hybrid trunk-mst

source [file join $::corpus::root {big_data_test/big2/tracks4top.tcl}]

buda::add_block {blk_01} {4145} {1000} {6100} {1425}
buda::add_block {blk_09} {3500} {2570} {4870} {3100}
buda::add_block {blk_19} {0} {2660} {1250} {3310}
buda::add_block {blk_34} {0} {1600} {1250} {2085}
buda::add_block {blk_39} {4870} {3365} {6100} {4425}
buda::add_block {io_pad_br} {5585} {0} {6100} {1000}
buda::add_net {bus_023[16]} {blk_01.p} {blk_34.p,blk_39.p,blk_09.p,blk_19.p,io_pad_br.p}

buda::run_bundler
buda::generate_topologies
buda::check_design {topo} {all}
buda::run_planner
buda::run_nuts
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design
buda::visualize

corpus::end [info script]
