# Generated by tools/buda2tcl.py from flow/big_data_test/big2/b4_bus_077.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big2/b4_bus_077.buda}
# One bundle from big2_b4_b24.buda
source [file join $::corpus::root {big_data_test/big2/tracks4top.tcl}]

buda::set_die {6100} {6300}
buda::add_block {blk_02} {4280} {5350} {5445} {6300}
buda::add_block {blk_12} {4870} {4425} {6100} {5350}
buda::add_block {blk_22} {4870} {2385} {6100} {3365}
buda::add_block {blk_29} {4870} {1425} {6100} {2385}
buda::add_block {io_pad_tr} {5445} {5350} {6100} {6300}

# --- bundle 4 (bus_077):
buda::add_bus {bus_077[60]} {blk_02.p} {blk_22.p,blk_12.p,blk_29.p,io_pad_tr.p}

buda::run_bundler

buda::detour_channel {N} {300} {E} {500}
buda::generate_topologies {double_detour}

# Flexible "root" trunk (coverage-driven span, under double_detour): the topology
# generator now emits TRUNK_V@x5772 — a single V spine inside io_pad_tr's x-span
# that taps all four right-column receivers (blk_22/blk_12/blk_29/io_pad_tr) by
# pass-through and stubs only the driver blk_02.  Previously this region-4 trunk
# was dropped (degenerate span) and the in-bbox V trunks pinched the io_pad_tr /
# driver stub.  Leave the planner free to choose (it routes cleanly); to study a
# specific candidate, pin it, e.g.:
#   select_topology 1 5     # TRUNK_V@x5772 (index may shift as generation evolves)
# Check the SELECTED topologies before planning so a topology-gen coverage gap is
# caught at the topo stage and can't be masked by a later NUTS/DNUTS change.
buda::check_design {topo}
buda::dump_topologies {--conn}
buda::run_planner
buda::dump_topologies {--conn}
buda::run_nuts
buda::check_design {nuts}
buda::run_detailed_nuts
buda::check_design
buda::visualize
corpus::finish [info script] {0}
