# Generated by tools/buda2tcl.py from flow/big_data_test/big2/big2.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/big_data_test/big2/big2.buda}
# copied over from tc3b_flat.buda (used to be a soft-link)
source [file join $::corpus::root {big_data_test/big2/tracks4top.tcl}]
source [file join $::corpus::root {big_data_test/big2/tc3b_flat_x5.tcl}]
buda::run_bundler
# nuts: 10 overlaps, dnuts: 168 opens
#generate_topologies double_detour
# nuts: 6 overlaps,  dnuts: 52
buda::generate_topologies
buda::check_design {topo} {all}
# This flow heals (ripup_reroute/negotiate_congestion below), so opt into the
# kSegsRel proactive default explicitly (issue #444 — replaces the old
# script-text lookahead so source/line-by-line/interactive all agree).
buda::set_planner_param {healersAhead} {1}
buda::run_planner {signal_tracks}
buda::run_nuts
buda::negotiate_congestion
# overlaps 2->0, but has no impact on DNUTS
buda::ripup_reroute
buda::check_design {nuts}
buda::run_detailed_nuts
buda::negotiate_congestion
# no help:
# ripup_reroute
buda::check_design
buda::visualize

corpus::end [info script]
