#!/usr/bin/env python3
# Copyright 2026 Ben Bulent Basaran
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Translate a `.buda` flow into the equivalent Tcl, driven through the front end.

A `.buda` script and a Tcl flow say the same things to the same engine — one
through the CLI's script reader, the other through `tools/buda.tcl` and the
command server.  That makes the pair a MEASUREMENT: run both and any
difference in the routed result is a fault in the bridge, not in the design.
`flow/tcl/corpus/` is that measurement at corpus scale (41 flows), and this is
the tool that keeps the two sides in step — a hand-written translation would
drift from its original the first time anyone edited the `.buda`.

What the translation preserves, and why each is not a detail:

* **One command per line, same order, same tokens.**  Arguments are
  whitespace-split exactly as the CLI splits them and handed over one Tcl word
  each; `buda.tcl` re-joins them with spaces, so the engine's handler sees the
  identical line.  Every word is brace-quoted, because a bus name like
  `bus[4]` is COMMAND SUBSTITUTION in Tcl and would otherwise run `4`.
* **Inline comments are stripped by the CLI's own helper**
  (`_strip_inline_comment`), imported rather than re-implemented: a second
  copy of that rule is a second thing to keep in step, and the rule has a
  subtlety worth not re-deriving (a `#` inside a token is not a comment).
* **`source` becomes Tcl's own `source`** of the translated sibling, so a
  shared fixture (`flow/tracks/tracks.buda`) is translated ONCE and composed
  by Tcl the way the CLI composes the original — rather than inlined 40 times.
  Resolved against the sourcing script's own directory, which is exactly the
  rule `resolve_script_path` gives the `.buda` side.
* **`exit` ends the run there.**  In a `.buda` that is the last thing that
  happens; through the pipe the engine process would end and its state — the
  thing we came to measure — would go with it.  So the epilogue runs at the
  `exit`, and anything after it is dropped, which is what the CLI does too.
  A NON-ZERO `exit <code>` is a real abort and is translated as one.

Usage:
  tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus       # the QoR corpus
  tools/buda2tcl.py --out-dir /tmp/x flow/rnr/mix.buda       # named flows
  tools/buda2tcl.py --check --corpus                         # drift guard
"""
import argparse
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
for _p in (os.path.join(_ROOT, "src"), os.path.join(_ROOT, "build"), _HERE):
    if _p not in sys.path:
        sys.path.insert(0, _p)

# The CLI's own comment rule, not a copy of it.
from buda_cli import _strip_inline_comment                    # noqa: E402
# Tcl quoting, shared with every test that writes a front-end preamble.
from tcl_quote import tcl_word, tcl_path, posix_sep           # noqa: E402,F401

BANNER = ("# Generated by tools/buda2tcl.py from {origin} — DO NOT EDIT.\n"
          "# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus\n")

# Boilerplate every translated file carries: find the corpus harness by walking
# up from this script's own directory, so a flow nested two levels deep
# (big_data_test/big2/...) needs no hard-coded depth.
PRELUDE = """
if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {%(origin)s}
"""


def translate_line(line, src_dir, out_root, flow_root):
    """One `.buda` line -> zero or more Tcl lines.

    Returns (tcl_lines, referenced_buda_path_or_None, ends_run_bool).
    """
    body = _strip_inline_comment(line).strip()
    raw = line.rstrip("\n")
    if not body:
        # Blank lines and whole-line comments carry the flow's own commentary;
        # a translation that dropped them would be harder to read against the
        # original, which is the one thing a generated file must stay easy to do.
        return ([raw if raw.startswith("#") or not raw.strip() else ""], None, False)
    toks = body.split()
    cmd = toks[0].lower()

    if cmd == "source" and len(toks) >= 2:
        # Anchored on the corpus ROOT, not on `[info script]`: the harness
        # `cd`s into the original flow's directory, and `file normalize` of a
        # relative script path resolves against the CURRENT directory — so the
        # obvious self-relative form silently starts looking for fixtures
        # under the flow's own tree.  `::corpus::root` is captured when the
        # harness is sourced, which is before that cd.
        ref = os.path.normpath(os.path.join(src_dir, toks[1]))
        # `source fixture` (no suffix) is legal: cmd_source falls back to
        # `fixture.buda` when the exact path is not a file.  Resolving it the
        # same way here is what lets such a flow be translated at all —
        # otherwise the queue tries to open a path that does not exist.
        if not os.path.isfile(ref) and not toks[1].endswith(".buda"):
            cand = os.path.normpath(os.path.join(src_dir, toks[1] + ".buda"))
            if os.path.isfile(cand):
                ref = cand
        rel = os.path.relpath(_out_path(ref, out_root, flow_root), out_root)
        # `tcl_path`, not `tcl_word`: `relpath` spells separators the
        # PLATFORM's way, so regenerating on Windows would emit `rnr\mix.tcl`
        # — which Tcl reads as an escape, and which would also read as drift
        # against the checked-in corpus.  Byte-identical on POSIX, where the
        # separators are already `/`.
        return ([f"source [file join $::corpus::root {tcl_path(rel)}]"],
                ref, False)

    if cmd == "exit":
        code = toks[1] if len(toks) > 1 else "0"
        # `corpus::finish`, which never returns — NOT a `return`.  In the CLI
        # `exit` raises SystemExit and unwinds the entire run, sourced files
        # included; a bare `return` here would only leave the Tcl `source`,
        # and the parent translation would carry on executing commands the
        # original never reached (Codex P2 on #686).  finish measures wherever
        # it is called from, because an exit anywhere IS the end of the run.
        return ([f"corpus::finish [info script] {tcl_word(code or '0')}"],
                None, True)

    return ([" ".join(["buda::" + cmd] + [tcl_word(t) for t in toks[1:]])],
            None, False)


def _out_path(buda_path, out_root, flow_root):
    """flow/rnr/mix.buda -> <out_root>/rnr/mix.tcl (layout mirrored)."""
    # The same Windows cross-drive case as `origin` below (Codex P2 on
    # #748): `main()` pins flow_root to the repo's flow/, so translating a
    # C:-temp flow against a D: checkout raised here even with the origin
    # fallback (the tests never hit it — they pass their own tmp
    # flow_root).  An out-of-tree flow has no layout to mirror, so its
    # translation lands at out_root's top level by basename.
    try:
        rel = os.path.relpath(os.path.abspath(buda_path), flow_root)
    except ValueError:
        rel = os.path.basename(buda_path)
    return os.path.join(out_root, os.path.splitext(rel)[0] + ".tcl")


def translate_file(buda_path, out_root, flow_root):
    """Translate one `.buda`; returns (out_path, text, [referenced .buda...])."""
    src_dir = os.path.dirname(os.path.abspath(buda_path))
    # `relpath` spells separators the PLATFORM's way, and origin is stamped
    # into line 1 of every generated file AND into `corpus::begin`.  Left
    # native, a Windows regeneration rewrites all 59 files to `flow\rnr\...`
    # and the drift guard reports the whole corpus stale (measured,
    # windows-validate run 24 on this branch).  The repo-relative spelling is
    # `/` on every platform, so this is byte-identical on POSIX.
    # A flow OUTSIDE the repo (a tmp vehicle) has no repo-relative spelling at
    # all on Windows when tmp and checkout sit on different drives —
    # `ntpath.relpath` raises ValueError there (measured, windows-validate
    # run 25: three test_tcl_corpus mini-flows died in translate_file) — so
    # the origin falls back to the absolute path, `/`-spelled.
    try:
        origin = posix_sep(os.path.relpath(os.path.abspath(buda_path), _ROOT))
    except ValueError:
        origin = posix_sep(os.path.abspath(buda_path))
    lines, refs, ended = [], [], False
    with open(buda_path) as fh:
        for line in fh:
            if ended:
                lines.append("# (unreachable in the original: after `exit`) "
                             + _strip_inline_comment(line).strip())
                continue
            tl, ref, ends = translate_line(line, src_dir, out_root, flow_root)
            lines.extend(tl)
            if ref:
                refs.append(ref)
            ended = ended or ends
    text = BANNER.format(origin=origin) + PRELUDE % {"origin": origin}
    text += "\n".join(lines).rstrip("\n") + "\n"
    if not ended:
        text += "\ncorpus::end [info script]\n"
    return _out_path(buda_path, out_root, flow_root), text, refs


def translate(flows, out_root, flow_root):
    """Translate `flows` and everything they `source`, transitively."""
    done, queue, written = set(), list(flows), {}
    while queue:
        f = os.path.abspath(queue.pop(0))
        if f in done:
            continue
        done.add(f)
        out, text, refs = translate_file(f, out_root, flow_root)
        written[out] = text
        queue.extend(refs)
    return written


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("flows", nargs="*", help=".buda flows to translate")
    ap.add_argument("--corpus", action="store_true",
                    help="translate the whole QoR corpus (tools/qor_corpus.py)")
    ap.add_argument("--out-dir", default=os.path.join(_ROOT, "flow/tcl/corpus"))
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if any file would change "
                         "(the drift guard)")
    a = ap.parse_args(argv)

    flows = list(a.flows)
    if a.corpus:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "qc", os.path.join(_HERE, "qor_corpus.py"))
        qc = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(qc)
        flows += [os.path.join(_ROOT, f) for f in qc.CORPUS]
    if not flows:
        ap.error("no flows: pass paths or --corpus")

    out_root = os.path.abspath(a.out_dir)
    written = translate(flows, out_root, os.path.join(_ROOT, "flow"))

    if a.check:
        stale = []
        for path, text in sorted(written.items()):
            try:
                with open(path) as fh:
                    if fh.read() == text:
                        continue
            except OSError:
                pass
            stale.append(os.path.relpath(path, _ROOT))
        if stale:
            print(f"{len(stale)} translated file(s) differ from their .buda "
                  f"source — regenerate with "
                  f"`tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus`:")
            for s in stale[:20]:
                print("   ", s)
            return 1
        print(f"{len(written)} translated file(s) up to date")
        return 0

    for path, text in sorted(written.items()):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(text)
    print(f"wrote {len(written)} file(s) -> {os.path.relpath(out_root, _ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
