#!/usr/bin/env python3
# Copyright 2026 Ben Bulent Basaran
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Build macOS .app launcher bundles for BUDA (bin/Buda.app) and the
Floorplanner (bin/Floorplanner.app).

Why a bundle at all? The bold menu-bar name, window title, and Dock *icon*
are already set at runtime (buda_viz.set_app_name / set_dock_icon). The one
surface no runtime API can rename for a terminal-launched interpreter is the
Dock *text label* — it is derived from the executable and cached by the Dock
when the app first registers with LaunchServices. Launching the exact same
python through a .app bundle fixes that: LaunchServices establishes the app
identity (name + icon) at launch, before the interpreter execs, so the Dock
tile reads "Buda" / "Floorplanner".

The bundles are thin: their CFBundleExecutable is a shell launcher that
resolves the repo root from its own location, sets PYTHONPATH, and execs the
real entrypoint (src/buda_cli.py / tools/bdb_floorplanner.py) with "$@". No
interpreter is copied — /usr/bin/env python3 resolves to whatever python is
on PATH (e.g. the active conda env), matching the bin/ wrappers.

Usage:
    python3 tools/make_macos_apps.py          # build both bundles into bin/
    python3 tools/make_macos_apps.py --force  # rebuild even if up to date

Run once (or after changing buda_icon.png). The bundles are host-specific
build products, so bin/*.app is git-ignored. Off macOS this still writes the
Info.plist + launcher (handy to inspect); the .icns step is skipped (it needs
Apple's sips/iconutil), and buda_viz.set_dock_icon() supplies the icon at
runtime anyway.
"""
import os
import stat
import subprocess
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)                       # repo root (parent of tools/)
_BIN = os.path.join(_ROOT, "bin")
_ICON_PNG = os.path.join(_ROOT, "buda_icon.png")

# (bundle name, entrypoint relative to repo root, bundle identifier)
_APPS = [
    ("Buda", "src/buda_cli.py", "com.buda.buda"),
    ("Floorplanner", "tools/bdb_floorplanner.py", "com.buda.floorplanner"),
]

_LAUNCHER = """\
#!/bin/bash
# Auto-generated by tools/make_macos_apps.py — do not edit by hand.
# Launcher for {name}.app: resolve the repo root from this script's location
# (bin/{name}.app/Contents/MacOS/{name} → up 4 dirs), set PYTHONPATH, and exec
# the real entrypoint. Launched through a .app so the macOS Dock tile shows
# "{name}" instead of "python3".
HERE="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" && pwd )"
ROOT="$( cd "$HERE/../../../.." && pwd )"     # MacOS → Contents → app → bin → root
export PYTHONPATH="$ROOT/build:$ROOT/tools:$PYTHONPATH"
exec /usr/bin/env python3 "$ROOT/{entry}" "$@"
"""


def _plist(name, identifier, with_icon):
    icon = (f"    <key>CFBundleIconFile</key><string>{name.lower()}</string>\n"
            if with_icon else "")
    return f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" \
"http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>{name}</string>
    <key>CFBundleDisplayName</key><string>{name}</string>
    <key>CFBundleExecutable</key><string>{name}</string>
    <key>CFBundleIdentifier</key><string>{identifier}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
{icon}    <key>NSHighResolutionCapable</key><true/>
    <key>LSMinimumSystemVersion</key><string>10.13</string>
</dict>
</plist>
"""


def _build_icns(dst_icns):
    """Render buda_icon.png → dst_icns via Apple's sips + iconutil.
    Returns True on success. No-op (False) if the PNG or the tools are absent
    (e.g. running off macOS) — set_dock_icon() covers the icon at runtime."""
    if not os.path.exists(_ICON_PNG):
        print(f"  (no {os.path.relpath(_ICON_PNG, _ROOT)} — skipping icon)")
        return False
    if not (_have("sips") and _have("iconutil")):
        print("  (sips/iconutil not found — skipping .icns; runtime sets the "
              "Dock icon instead)")
        return False
    with tempfile.TemporaryDirectory() as tmp:
        iconset = os.path.join(tmp, "icon.iconset")
        os.makedirs(iconset)
        for size in (16, 32, 128, 256, 512):
            for scale, suffix in ((1, ""), (2, "@2x")):
                px = size * scale
                out = os.path.join(iconset, f"icon_{size}x{size}{suffix}.png")
                if subprocess.call(
                        ["sips", "-z", str(px), str(px), _ICON_PNG, "--out", out],
                        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL) != 0:
                    print("  (sips failed — skipping icon)")
                    return False
        if subprocess.call(["iconutil", "-c", "icns", iconset, "-o", dst_icns],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL) != 0:
            print("  (iconutil failed — skipping icon)")
            return False
    return True


def _have(cmd):
    return subprocess.call(["which", cmd], stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL) == 0


def _write(path, text, executable=False):
    with open(path, "w") as f:
        f.write(text)
    if executable:
        st = os.stat(path)
        os.chmod(path, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def build_app(name, entry, identifier):
    app = os.path.join(_BIN, f"{name}.app")
    contents = os.path.join(app, "Contents")
    macos = os.path.join(contents, "MacOS")
    resources = os.path.join(contents, "Resources")
    for d in (macos, resources):
        os.makedirs(d, exist_ok=True)

    icns = os.path.join(resources, f"{name.lower()}.icns")
    with_icon = _build_icns(icns)

    _write(os.path.join(contents, "Info.plist"),
           _plist(name, identifier, with_icon))
    _write(os.path.join(macos, name),
           _LAUNCHER.format(name=name, entry=entry), executable=True)
    print(f"  built {os.path.relpath(app, _ROOT)}  (entry: {entry}"
          f"{', icon' if with_icon else ''})")


def main():
    if not os.path.isdir(_BIN):
        sys.exit(f"error: {_BIN} not found — run from a BUDA checkout")
    if sys.platform != "darwin":
        print("note: not on macOS — writing Info.plist + launcher for "
              "inspection; the .icns step needs Apple's sips/iconutil.")
    print(f"Building macOS app bundles into {os.path.relpath(_BIN, _ROOT)}/ …")
    for spec in _APPS:
        build_app(*spec)
    print("Done. Launch e.g.  open -a bin/Floorplanner.app --args foo.bdb\n"
          "      or double-click the bundle in Finder / drag it to the Dock.")


if __name__ == "__main__":
    main()
