# Generated by tools/buda2tcl.py from flow/tracks/tracks4top.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/tracks/tracks4top.buda}
# From tracks_for_channel_stress.buda, but with four top:

buda::def_layer {2} {M2} {H} {LOW} {55.56}
buda::def_layer {3} {M3} {V} {LOW} {55.56}
buda::def_layer {4} {M4} {H} {TOP} {55.56}
buda::def_layer {5} {M5} {V} {TOP} {55.56}
buda::def_layer {6} {M6} {H} {TOP} {66.67}
buda::def_layer {7} {M7} {V} {TOP} {58.97}

# Track patterns are REQUIRED for Detailed NUTS
# Format: <layer_id> <origin> [<type> <width> <spacing>] ...
buda::def_track_pattern {2} {-100} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {3} {0} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {4} {-200} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {5} {0} {POWER} {2} {1} {(SIGNAL} {1} {0.5)x4} {GROUND} {2} {1} {(SIGNAL} {1} {0.5)x4}
buda::def_track_pattern {6} {-400} {POWER} {3} {1} {(SIGNAL} {1} {1)x4} {GROUND} {3} {1} {(SIGNAL} {1} {1)x4}
buda::def_track_pattern {7} {-600} {POWER} {6} {2} {(SIGNAL} {2} {1)x4} {GROUND} {6} {1} {(SIGNAL} {2} {1)x4}

buda::report_overhead

corpus::end [info script]
