# Generated by tools/buda2tcl.py from flow/rnr/mix.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/rnr/mix.buda}
source [file join $::corpus::root {rnr/mix_tracks.tcl}]
# Diffable serialized BDB (see docs/internal/bdb_test_data.md): open_bdb loads the
# *.sql text into a throwaway temp binary, so this flow never dirties the fixture.
buda::open_bdb {mix.bdb.sql}
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::run_hier_bundler {depth} {2}
buda::dump_hbundles
# Midpoint-only pool (hanan_loci default-flip opt-out, owner decision): this
# flow's fully-healed 0 overlaps / 0 opens endpoint is a regression target,
# and the default-on loci pool regresses it to 42 dnuts-unplaced (2 bundles)
# at det WL +0.13% with no DISCONNECTED involved — see wishlist-topo
# "Nominal-WL comparability" piece (a) (final flip table + the mix-loci
# root-cause follow-on).
buda::generate_hier_topologies {no_hanan_loci}
# improvement (1) due to signal_tracks:
# Heals below → opt into the kSegsRel proactive default explicitly (issue #444).
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
# improvement (2) negotiated congestion: feed the measured NUTS overlaps
# back into the planner as band demand (bundles re-route by cost, no
# trial-and-error), then the rnr stage-a hill-climb finishes the residual:
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design {nuts}
buda::report_wirelength
buda::run_detailed_nuts
# improvement (3) (rnr stage b) to reduce number of bit seg opens — negotiate
# first (each open segment's window is injected as band demand, teaching the
# planner what DetailedNUTS measured), then the hill-climb finishes:
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design {dnuts}
buda::report_wirelength
buda::visualize

corpus::end [info script]
