# Generated by tools/buda2tcl.py from flow/rnr/mix2_fast_topdown.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/rnr/mix2_fast_topdown.buda}
source [file join $::corpus::root {rnr/mix_tracks.tcl}]
buda::open_bdb {mix2.bdb.sql}
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::run_hier_bundler {depth} {2}
# dump_hbundles
buda::generate_hier_topologies
# NOTE: deliberately does NOT declare `set_planner_param healersAhead 1`
# (mix2.buda, its parent, does) even though it heals below.  Measured
# 2026-08-03: declaring holds QoR (0/0/0) but costs +8.0% detailed WL.
# See docs/internal/ksegs_default_audit.md.
buda::run_planner {hier} {5} {signal_tracks}
buda::dump_topologies
buda::run_nuts
# Healing stage a: negotiate the measured NUTS overlaps as band demand,
# then the rnr hill-climb finishes the residual.
buda::negotiate_congestion
buda::ripup_reroute
buda::run_detailed_nuts
# Healing stage b: negotiate each DNUTS-open segment's window, then hill-climb.
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design
buda::visualize
corpus::end [info script]   ;# `exit` in the original
return
