# Generated by tools/buda2tcl.py from flow/rnr/mix2_fast_bottomup.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/rnr/mix2_fast_bottomup.buda}
source [file join $::corpus::root {rnr/mix_tracks.tcl}]
buda::open_bdb {mix2.bdb.sql}

# Bottom-up: plan/NUTS each cell template once, copy to all instances.
# Must come after open_bdb (flags persist in the BDB) and before run_planner hier.
buda::set_bottom_up {dnuts1}
buda::set_bottom_up {dnuts2}
buda::set_bottom_up {dogleg1}
buda::set_bottom_up {dogleg2}

buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::run_hier_bundler {depth} {2}
# dump_hbundles
buda::generate_hier_topologies
# NOTE: deliberately does NOT declare `set_planner_param healersAhead 1`
# (mix2.buda, its parent, does) even though it heals below.  Measured
# 2026-08-03: declaring is QoR-neutral here (0/0/0 either way) but moves
# detailed WL +0.6%; it buys nothing.  See docs/internal/ksegs_default_audit.md.
buda::run_planner {hier} {5} {signal_tracks}
buda::dump_topologies
buda::run_nuts
# Healing stage a: feed the measured NUTS overlaps back as band demand
# (negotiate), then the rnr hill-climb finishes the residual — the locked
# bottom-up copies are respected (never re-routed).
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design {nuts}
buda::check_template_tracks {on_mismatch} {independent}
buda::run_detailed_nuts
# Healing stage b: negotiate each DNUTS-open segment's window, then hill-climb.
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design
buda::visualize
corpus::end [info script]   ;# `exit` in the original
return
