# Generated by tools/buda2tcl.py from flow/rnr/mix2.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/rnr/mix2.buda}
source [file join $::corpus::root {rnr/mix_tracks.tcl}]
buda::open_bdb {mix2.bdb.sql}
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::run_hier_bundler {depth} {2}
buda::dump_hbundles
buda::generate_hier_topologies
# Heals below → opt into the kSegsRel proactive default explicitly (issue #444).
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design {nuts}
buda::run_detailed_nuts
buda::negotiate_congestion
buda::ripup_reroute
#
# KNOWN REGRESSION (issue #518).  This flow is the one corpus vehicle that the
# `band_span_charge` default flip costs: it now ends 0 overlaps / 16 unplaced
# bits (bundle 61 seg 2, "no track in DetailedNUTS") instead of the fully
# clean 0/0 it reached before.  The stage-b hill-climb runs to a genuine stall
# (42 (ovl 2) -> 16 (ovl 0), 5 moves, 511 trials, "no improving re-route"), so
# this is NOT a healer-budget shortfall — it is the absolute-supply blind
# spot: the width books say the spread bus fits, but DetailedNUTS still needs
# real SIGNAL tracks at the placed position.  Three repair attempts (kPeak
# pairing, contiguity, a spread-local supply guard) were measured and all lost
# corpus-wide; see docs/internal/band_span_charge.md.
#
# Uncomment to restore the historical clean endpoint on this flow:
#set_planner_param band_span_charge 0    # (put it BEFORE run_planner above)
#
# The override is deliberately NOT applied here.  Silencing the one flow that
# regressed would make the QoR corpus report 3 better / 0 worse and quietly
# retire a known real cost; leaving it visible is the point.
#
# The historical trace, for reference (pre-flip, band_span_charge 0):
#[ripup_reroute] iter 1: COMMIT bundle 11 topo 2->5, metric 18 (ovl 2)->10 (ovl 1)
#[ripup_reroute] iter 2: COMMIT bundle 13 topo 6->1, metric 10 (ovl 1)->4 (ovl 1)
#[ripup_reroute] iter 3: COMMIT bundle 146 topo 1->5, metric 4 (ovl 1)->0 (ovl 1)
#[ripup_reroute] iter 4: COMMIT bundle 174 topo 2->4, metric 0 (ovl 1)->0 (ovl 0)

buda::check_design {dnuts}
buda::report_wirelength
buda::visualize

corpus::end [info script]
