# Generated by tools/buda2tcl.py from flow/rnr/mix2_fast_bottomup_shared.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/rnr/mix2_fast_bottomup_shared.buda}
source [file join $::corpus::root {rnr/mix_tracks.tcl}]
buda::open_bdb {mix2.bdb.sql}

# Bottom-up: plan/NUTS each cell template once, copy to all instances.
buda::set_bottom_up {dnuts1}
buda::set_bottom_up {dnuts2}
buda::set_bottom_up {dogleg1}
buda::set_bottom_up {dogleg2}

# The WIRING-LIMITED shared vehicle (docs/internal/hier_layer_caps.md §12,
# Phase 3): the caps vehicle measured that dnuts1's 32-bit cell-local buses
# genuinely exceed the LOW pair's supply (M3-capped it commits with planner
# overflow 13-35.5 and strands all 32 bits at DNUTS).  Instead of the mid
# band, dnuts1 keeps the M3 cap and LEASES a bounded slice of M4/M5 — the
# escape valve the shares exist for: the cell-local solve prices the leased
# slice at its thinned bit pitch and spills only what M2/M3 cannot carry;
# the parent keeps everything the lease leaves unused (budget, not
# reservation).  The other leaf cells stay hard-capped as in the caps twin.
buda::set_cell_layer_cap {dnuts1} {M3}
buda::set_cell_layer_share {dnuts1} {M4} {75}
buda::set_cell_layer_share {dnuts1} {M5} {75}
buda::set_cell_layer_cap {dnuts2} {M3}
buda::set_cell_layer_cap {dogleg1} {M5}
buda::set_cell_layer_cap {dogleg2} {M5}

buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::run_hier_bundler {depth} {2}
buda::generate_hier_topologies
# NOTE: deliberately does NOT declare `set_planner_param healersAhead 1`
# (mix2.buda, its parent, does) even though it heals below.  Measured
# 2026-08-03: declaring REGRESSES this flow badly — 0/0/0 -> 10 overlaps /
# 112 unplaced / 13 viol_bundles.  Do not 'fix' this.
# See docs/internal/ksegs_default_audit.md.
buda::run_planner {hier} {5} {signal_tracks}
buda::dump_topologies
buda::run_nuts
# Healing stage a: negotiate the measured NUTS overlaps, then the rnr
# hill-climb finishes the residual (locked bottom-up copies respected).
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design {nuts}
buda::check_template_tracks {on_mismatch} {independent}
buda::run_detailed_nuts
# Healing stage b: negotiate each DNUTS-open segment's window, then hill-climb.
buda::negotiate_congestion
buda::ripup_reroute
buda::check_design
buda::report_wirelength
buda::visualize
corpus::finish [info script] {0}
