# Generated by tools/buda2tcl.py from flow/chip/chip_bottomup.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip_bottomup.buda}
# chip — the next-level hier vehicle, BOTTOM-UP variant: mark both cell
# templates (big2 + mix2) for bottom-up planning — each cell's local
# interconnect is planned/NUTS'd ONCE and copied to its three instances (the
# copies become keepouts for the top-level buses) — with OCCURRENCE ALIGNMENT:
# align_bottom_up nudges the instances of each cell onto a common track phase
# (minimal total movement, per rotation class) so the copied routing lands on
# real tracks at every occurrence and check_template_tracks agrees.  Order
# matters: set_bottom_up + align_bottom_up run after open_bdb (flags persist in
# the BDB; align needs the track pitches from chip_tracks) and BEFORE
# derive_busterms / add_blocks_from_bdb.  Heals with negotiate_congestion
# only; drop that line (and healersAhead) for the healerless fast mode.
source [file join $::corpus::root {chip/chip_tracks.tcl}]
buda::open_bdb {chip.bdb.sql}
buda::set_bottom_up {big2}
buda::set_bottom_up {mix2}
buda::align_bottom_up
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::set_max_bundle_bits {auto}
buda::run_hier_bundler {depth} {2}
buda::generate_hier_topologies
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::check_template_tracks {on_mismatch} {independent}
buda::run_detailed_nuts
buda::negotiate_congestion
buda::report_wl
buda::check_design
corpus::finish [info script] {0}
