# Generated by tools/buda2tcl.py from flow/chip/chip3_topdown.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip3_topdown.buda}
# chip3 — the TRUE 3-LEVEL variant of chip_topdown (2026-07-31): same
# composition (3x big2 + 3x mix2 + 100 top buses, identical SA placement),
# but mix2 is imported with build_hier_demo's --nest-bdb-cells, PRESERVING
# its internal hierarchy instead of flattening it one level:
#   chip (d0) -> i_big2_k / i_mix2_k (d1) -> big2 blocks + i_dnuts*_j (d2)
#     -> mix2 leaf blocks (d3)
# 1 + 6 + 192 + 300 components, 13320 nets (deep names like
# chip/i_mix2_0/i_dnuts1_0/bv1_0).  Busterms derived to depth 3, blocks
# loaded at every depth incl. 3, bundler reaches depth 3 — the maiden
# depth-3 run of the hier pipeline.  Heals with negotiate_congestion only,
# like chip_topdown.
source [file join $::corpus::root {chip/chip_tracks.tcl}]
buda::open_bdb {chip3.bdb.sql}
buda::derive_busterms {3}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::add_blocks_from_bdb {3} {skip}
buda::set_max_bundle_bits {auto}
buda::run_hier_bundler {depth} {3}
buda::generate_hier_topologies
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::run_detailed_nuts
buda::negotiate_congestion
buda::report_wl
buda::check_design
corpus::end [info script]   ;# `exit` in the original
return
