# Generated by tools/buda2tcl.py from flow/chip/chip_tracks.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip_tracks.buda}
# The shared 10-layer chip stack: M2/M3 LOW plus eight TOP layers M4-M11, each
# pair coarser than the one below it, as real top metal is.
#
# SYMMETRIC UNITS, 16 SIGNAL TRACKS PER PERIOD.
#
# Every repeating unit is a PALINDROME: each rail carries the same gap before
# it as after it, so the pattern is invariant under reflection and a flipped
# instance's routing can land on real tracks.  (The gaps used to be lopsided —
# M2/M4 had 1 after a rail and 0.5 before — which left the H layers with NO
# reflection axis at any origin; see flow/chip/ReadMe.md.  Symmetry alone does
# not align a mirrored design: the ORIGIN has to put an axis on the instance
# centrelines, which is what chip_tracks_mirror.buda adds on top of this.)
#
# SIXTEEN signals per period rather than the historical eight — eight per group
# — and 16 = 2x8 is what makes this clean: every signal width and spacing simply
# HALVES, and the gap g around each rail absorbs the rest.  Three consequences,
# all of them exact rather than approximate:
#
#   * the PERIOD of every layer is unchanged, so the 504 = LCM(18,18,24,56)
#     placement grid, `align_bottom_up` and every checked-in floorplan hold;
#   * the signal METAL per period is unchanged on every layer (16 x w/2 == 8 x w),
#     so the def_layer overheads below are the HISTORICAL numbers, untouched;
#   * the bit pitch is exactly HALF the historical period/8.
#
# EVERY VALUE IS BINARY-EXACT, and that is a HARD REQUIREMENT, not cosmetics.
# `tracks_in_range` walks a period at a time with `pos += width + space_after`,
# so hundreds of periods of accumulated rounding decide whether a track sitting
# exactly ON a window edge is inside it.  An earlier cut of this stack used ten
# signals per period via the arithmetically obvious scaling — width and spacing
# x 8/10, which also holds the metal exactly constant — giving 0.8 / 0.4 / 0.7 …
# and not one of those values is representable in binary.  The result was an
# off-by-one track at window edges that broke template alignment:
# check_template_tracks reported "397 vs 396", both cells went MISALIGNED, and
# the mirrored stack copied ZERO bits, on a placement that had not changed.
#
# Doubling has no such tension: halving a binary-exact value is binary-exact, so
# 16 tracks keeps BOTH the exact metal and the exact arithmetic, which 10 could
# not.  That is the reason to jump to 2x rather than creep to 10 or 12.
#
#   layer  period  rail   w     s      g      overhead   bit pitch (was)
#   M2-M5    18     2    0.5   0.25   0.625    55.56%     1.125  (2.25)
#   M6       24     3    0.5   0.5    0.75     66.67%     1.500  (3.00)
#   M7       39     6    1     0.5    1        58.97%     2.438  (4.875)
#   M8/M9    56     8    1.5   0.75   1.375    57.14%     3.500  (7.00)
#   M10/M11  74    10    2     1      2        56.76%     4.625  (9.25)
#
# The cost is OUTSIDE this model: minimum feature halves (M2 signal 1 -> 0.5,
# spacing 0.5 -> 0.25 against the historical technology).  Whether that is
# manufacturable is a technology decision, not a routing one.
#
# Overhead percentages are the patterns' measured values (1 - signal density) —
# see report_overhead below.
buda::def_layer {2} {M2} {H} {LOW} {55.56}
buda::def_layer {3} {M3} {V} {LOW} {55.56}
buda::def_layer {4} {M4} {H} {TOP} {55.56}
buda::def_layer {5} {M5} {V} {TOP} {55.56}
buda::def_layer {6} {M6} {H} {TOP} {66.67}
buda::def_layer {7} {M7} {V} {TOP} {58.97}
buda::def_layer {8} {M8} {H} {TOP} {57.14}
buda::def_layer {9} {M9} {V} {TOP} {57.14}
buda::def_layer {10} {M10} {H} {TOP} {56.76}
buda::def_layer {11} {M11} {V} {TOP} {56.76}

# Track patterns are REQUIRED for Detailed NUTS.
# Format: <layer_id> <origin> [<type> <width> <spacing>] ...
buda::def_track_pattern {2} {-100} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {3} {0} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {4} {-200} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {5} {0} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {6} {-400} {POWER} {3} {0.75} {(SIGNAL} {0.5} {0.5)x7} {SIGNAL} {0.5} {0.75} {GROUND} {3} {0.75} {(SIGNAL} {0.5} {0.5)x7} {SIGNAL} {0.5} {0.75}
buda::def_track_pattern {7} {-600} {POWER} {6} {1} {(SIGNAL} {1} {0.5)x7} {SIGNAL} {1} {1} {GROUND} {6} {1} {(SIGNAL} {1} {0.5)x7} {SIGNAL} {1} {1}
buda::def_track_pattern {8} {-800} {POWER} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375} {GROUND} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375}
buda::def_track_pattern {9} {-1000} {POWER} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375} {GROUND} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375}
buda::def_track_pattern {10} {-1200} {POWER} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2} {GROUND} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2}
buda::def_track_pattern {11} {-1400} {POWER} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2} {GROUND} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2}

buda::report_overhead

corpus::end [info script]
