# Generated by tools/buda2tcl.py from flow/chip/chip_stack_bottomup.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip_stack_bottomup.buda}
# chip_stack — the ON-GRID STACKED chip variant, BOTTOM-UP.
#
# Same two cell types as chip.bdb.sql, placed deliberately instead of by SA:
#
#   LEFT  column  x=[0..6100]      2 x big2, pitch 7560  (cell 6300 + ch 1260)
#                                  y = 0, 7560
#   RIGHT column  x=[7100..9430]   4 x mix2, pitch 3528  (cell 2360 + ch 1168)
#                                  y = 458, 3986, 7514, 11042
#   die 9430 x 13860, 100 top-level cross-hierarchy buses, 11750 nets
#
# MIRROR-SYMMETRIC, ON GRID.  Columns are CENTRED (--column-align center: mix2
# gets 458 margin top and bottom, which is forced — zero margins are
# arithmetically impossible when the channels must be ≡160 mod 504) and the
# three instances above y=6930 are FLIPPED upside down (--mirror-upper), so all
# 488 leaf blocks map exactly onto their reflections about the centreline.
#
# THE MIRROR NEEDS A MIRROR-SYMMETRIC TECHNOLOGY, which is why this vehicle
# sources chip_tracks_MIRROR.buda rather than chip_tracks.buda.  A flipped
# instance's routing is its reference's reflected about the instance's own
# centreline, so the H patterns must be invariant under that reflection — the
# centreline must land on a reflection AXIS.  Two independent requirements:
# the pattern must HAVE axes (be a palindrome), which the shared
# chip_tracks.buda now satisfies on every layer; and the ORIGIN must put one ON
# the centrelines, which is placement-specific and is the ONLY thing this file
# changes — three H origins, M4 -199 / M6 -403.5 / M8 -802.  Every slot is
# byte-identical to the shared stack.
#
# Both cells report ALIGNED and solve-once-copy carries the mirror:
#
#   chip_tracks origins:  3262 bits copied to 100 siblings, 18089 solved alone
#   chip_tracks_mirror:  17875 bits copied to 380 siblings,  3971 solved alone
#
# `on_mismatch independent` is kept as a safety net, not because it is needed.
# Endpoints, the isolating control, and the retraction of some earlier numbers
# are in flow/chip/ReadMe.md.
#
# WHY IT IS ON GRID.  Every instance of a cell shares ONE x, so their vertical
# (V-layer) track phase is identical by construction.  The vertical pitches are
# multiples of 504 = LCM(18, 18, 24, 56) — the unit pitches of M2/M4/M6/M8, the
# HORIZONTAL layers a cell may use under `reserve_top_layers 2` — so the
# horizontal phase is identical too.  Delta-y contributes ZERO track offset
# between stacked instances.
#
# `align_bottom_up` is NOT called here: the UNFLIPPED instances are already
# phase-aligned as placed (compare chip_bottomup.buda, which must nudge an SA
# placement onto a common phase first).  Drop --mirror-upper from the generator
# line and every cell reports ALIGNED.
#
# The 504 grid is only valid while the cells stay at or below M9: the full
# 10-layer stack would need LCM(18,18,24,56,74) = 18648, which for a 6300-tall
# cell is 12k of dead channel.  Reserving the top pair is what makes a tight
# on-grid pitch affordable — so this vehicle declares it.
#
# Regenerate the BDB with:
#   python3 tools/build_hier_demo.py flow/chip/chip_stack.bdb \
#     --cells big2=flow/big_data_test/big2/tc3b_flat_x5.buda,mix2=flow/rnr/mix2.bdb.sql \
#     --instances big2=2,mix2=4 --buses 100 \
#     --layout stacked --channel 1000 --grid 504 \
#     --column-align center --mirror-upper
#   python3 tools/bdb_serialize.py dump flow/chip/chip_stack.bdb flow/chip/chip_stack.bdb.sql
source [file join $::corpus::root {chip/chip_tracks_mirror.tcl}]
buda::open_bdb {chip_stack.bdb.sql}
buda::set_bottom_up {big2}
buda::set_bottom_up {mix2}
# No align_bottom_up: the placement is already on the track grid.
buda::reserve_top_layers {2}
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::set_max_bundle_bits {auto}
buda::run_hier_bundler {depth} {2}
buda::generate_hier_topologies
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::check_template_tracks {on_mismatch} {independent}
buda::run_detailed_nuts
buda::negotiate_congestion
buda::report_wl
buda::check_design
corpus::end [info script]   ;# `exit` in the original
return
