# Generated by tools/buda2tcl.py from flow/chip/chip_tracks_mirror.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip_tracks_mirror.buda}
# chip_tracks, with the H ORIGINS PLACED FOR A MIRRORED LAYOUT.
#
# The PATTERNS here are byte-identical to chip_tracks.buda — same stack, same
# widths, same 10 signals per period, same periods, same overheads, same 504
# grid.  THE ONLY DIFFERENCE IS THREE H ORIGINS: M4 -199, M6 -403.5, M8 -802
# (against -200 / -400 / -800).  Everything else in this file is a copy.
#
# WHY A SEPARATE FILE.  A flipped instance's routing is its reference's routing
# reflected about the instance's own centreline, so the layer's pattern must be
# invariant under that reflection — the centreline must land on a reflection
# AXIS of the pattern.  Two things are needed and they are independent:
#
#   1. the pattern must HAVE axes at all -- it must be a palindrome.  That is
#      now true in chip_tracks.buda itself (each rail centred in its gap), so
#      this file inherits it and no longer has to change any slot.
#   2. the ORIGIN must put an axis ON the instance centrelines.  That is what
#      is left, and it is placement-specific, which is why it cannot live in
#      the shared file: chip_stack's three flipped instances sit at centres
#      8694 / 10710 / 12222, all differing by multiples of 504, so one origin
#      per layer serves all three -- but they are THIS design's centres.
#
# The condition is  instance_centre - origin == axis  (mod period/2), and each
# layer's axis sits at the power-rail centre (rail/2), so:
#
#   layer  period  axis (mod p/2)  origin  shift
#   M2       18     1  (mod 9)     -100    none needed
#   M4       18     1  (mod 9)     -199    +1
#   M6       24     1.5 (mod 12)   -403.5  -3.5
#   M8       56     4  (mod 28)    -802    -2
#
# M10 CANNOT be satisfied and does not need to be: its half period 37 does not
# divide 504, so the three flipped centres fall on three different residues and
# no single origin serves them.  That is precisely why `reserve_top_layers 2`
# caps cells at M9 — the grid is the LCM over the layers the CELLS use, and M10
# is not one of them.
#
# The V origins are the shared file's: an upside-down flip maps y -> 2d-y and
# leaves x alone, so vertical tracks take no part in this.
buda::def_layer {2} {M2} {H} {LOW} {55.56}
buda::def_layer {3} {M3} {V} {LOW} {55.56}
buda::def_layer {4} {M4} {H} {TOP} {55.56}
buda::def_layer {5} {M5} {V} {TOP} {55.56}
buda::def_layer {6} {M6} {H} {TOP} {66.67}
buda::def_layer {7} {M7} {V} {TOP} {58.97}
buda::def_layer {8} {M8} {H} {TOP} {57.14}
buda::def_layer {9} {M9} {V} {TOP} {57.14}
buda::def_layer {10} {M10} {H} {TOP} {56.76}
buda::def_layer {11} {M11} {V} {TOP} {56.76}

# H layers — symmetric units (rail centred in its gap), periods unchanged.
buda::def_track_pattern {2} {-100} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {4} {-199} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {6} {-403.5} {POWER} {3} {0.75} {(SIGNAL} {0.5} {0.5)x7} {SIGNAL} {0.5} {0.75} {GROUND} {3} {0.75} {(SIGNAL} {0.5} {0.5)x7} {SIGNAL} {0.5} {0.75}
buda::def_track_pattern {8} {-802} {POWER} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375} {GROUND} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375}
buda::def_track_pattern {10} {-1200} {POWER} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2} {GROUND} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2}

# V layers — unchanged from chip_tracks.buda (a y-flip does not move them).
buda::def_track_pattern {3} {0} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {5} {0} {POWER} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625} {GROUND} {2} {0.625} {(SIGNAL} {0.5} {0.25)x7} {SIGNAL} {0.5} {0.625}
buda::def_track_pattern {7} {-600} {POWER} {6} {1} {(SIGNAL} {1} {0.5)x7} {SIGNAL} {1} {1} {GROUND} {6} {1} {(SIGNAL} {1} {0.5)x7} {SIGNAL} {1} {1}
buda::def_track_pattern {9} {-1000} {POWER} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375} {GROUND} {8} {1.375} {(SIGNAL} {1.5} {0.75)x7} {SIGNAL} {1.5} {1.375}
buda::def_track_pattern {11} {-1400} {POWER} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2} {GROUND} {10} {2} {(SIGNAL} {2} {1)x7} {SIGNAL} {2} {2}

buda::report_overhead

corpus::end [info script]
