# Generated by tools/buda2tcl.py from flow/chip/chip_stack_topdown.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip_stack_topdown.buda}
# chip_stack — the ON-GRID STACKED chip variant, TOP-DOWN.
#
# The comparison twin of chip_stack_bottomup.buda: same design, same layer
# policy, SAME TRACK TECHNOLOGY, but no bottom-up templates — every instance's
# interconnect is planned individually in the global frame.  Use the pair to
# separate what the on-grid stacked placement buys from what solve-once-copy
# buys; that only works if both halves route on the same technology, so this
# one sources chip_tracks_mirror.buda too.
#
# It gains nothing from the mirror-symmetric ORIGINS (no templates, so nothing
# to keep in phase); what it does gain is the shared stack's extra tracks —
# 277/3262/161 before the 8 -> 10 track change, 103/2053/125 after.  The
# origins-only part of the pair is the piece it cannot use, which is the point:
# symmetry earns its keep exactly where solve-once-copy is in play.
#
# Design (see chip_stack_bottomup.buda for the full note on the 504 grid):
#   LEFT  column  x=[0..6100]      2 x big2, pitch 7560  (multiple of 504)
#   RIGHT column  x=[7100..9430]   4 x mix2, pitch 3528  (multiple of 504),
#                                  centred (458 margins); upper half mirrored
#   die 9430 x 13860, 100 top-level cross-hierarchy buses, 11750 nets
source [file join $::corpus::root {chip/chip_tracks_mirror.tcl}]
buda::open_bdb {chip_stack.bdb.sql}
buda::reserve_top_layers {2}
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::set_max_bundle_bits {auto}
buda::run_hier_bundler {depth} {2}
buda::generate_hier_topologies
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::run_detailed_nuts
buda::negotiate_congestion
buda::report_wl
buda::check_design
corpus::end [info script]   ;# `exit` in the original
return
