# Generated by tools/buda2tcl.py from flow/chip/chip3a_bottomup.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip3a_bottomup.buda}
# chip3 — depth-3 BOTTOM-UP variant: bottom-up marks at TWO hierarchy
# levels (templates within templates — a first): the depth-1 cells (big2,
# mix2) AND mix2's nested depth-2 cell types (mix2__dnuts1/2, mix2__dogleg1/2
# — 18/18/12/12 congruent occurrences each across the three mix2 copies).
# align_bottom_up nudges every marked cell's instances onto a common track
# phase; check_template_tracks arbitrates before DNUTS copies.  Heals with
# negotiate_congestion only, like the other chip flows.
source [file join $::corpus::root {chip/chip_tracks.tcl}]
buda::open_bdb {chip3a.bdb.sql}
buda::set_bottom_up {big2}
buda::set_bottom_up {mix2}
buda::set_bottom_up {mix2__dnuts1}
buda::set_bottom_up {mix2__dnuts2}
buda::set_bottom_up {mix2__dogleg1}
buda::set_bottom_up {mix2__dogleg2}
buda::align_bottom_up
buda::derive_busterms {3}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::add_blocks_from_bdb {3} {skip}
buda::set_max_bundle_bits {auto}
buda::run_hier_bundler {depth} {3}
buda::generate_hier_topologies
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::check_template_tracks {on_mismatch} {independent}
buda::run_detailed_nuts
buda::negotiate_congestion
buda::report_wl
buda::check_design
corpus::finish [info script] {0}
