# Generated by tools/buda2tcl.py from flow/chip/chip_topdown.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip_topdown.buda}
# chip — the next-level hier vehicle (2026-07-30): three instances each of
# big2 (flow/big_data_test/big2/tc3b_flat_x5.buda, 44 blocks / 2840 nets, as a
# flat-script cell) and mix2 (flow/rnr/mix2.bdb.sql, 100 leaf blocks / 1270
# nets, imported as a BDB cell — build_hier_demo's one-level flatten), SA-placed
# with 25% bloat channels, plus 100 random cross-instance top buses:
# 6 instances, 432 leaf blocks, 13320 nets.  Rebuild recipe (deterministic
# iteration budget) in flow/chip/ReadMe.md.
#
# TOP-DOWN variant: the plain hier pipeline, healed with negotiate_congestion
# ONLY.  ripup_reroute is not affordable at this scale — it ran >10 minutes
# without converging here against a 135s base flow — and refine_selection is an
# end-of-flow WL polish that wants a converged endpoint.  For the healerless
# fast-iteration mode drop the negotiate_congestion line and the
# `set_planner_param healersAhead 1` above it; see flow/chip/ReadMe.md.
source [file join $::corpus::root {chip/chip_tracks.tcl}]
buda::open_bdb {chip.bdb.sql}
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::set_max_bundle_bits {auto}
buda::run_hier_bundler {depth} {2}
buda::generate_hier_topologies
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::run_detailed_nuts
buda::negotiate_congestion
buda::report_wl
buda::check_design
corpus::finish [info script] {0}
