# Generated by tools/buda2tcl.py from flow/chip/chip_bottomup_caps.buda — DO NOT EDIT.
# Regenerate: tools/buda2tcl.py --out-dir flow/tcl/corpus --corpus

if {![namespace exists ::corpus]} {
    set _d [file dirname [file normalize [info script]]]
    while {![file exists [file join $_d harness.tcl]]} {
        set _p [file dirname $_d]
        if {$_p eq $_d} { error "corpus harness.tcl not found above [info script]" }
        set _d $_p
    }
    source [file join $_d harness.tcl]
}
corpus::begin [info script] {flow/chip/chip_bottomup_caps.buda}
# chip — BOTTOM-UP + BY-DEPTH LAYER CAPS: the chip-scale policy vehicle
# (docs/internal/hier_layer_caps.md §12/§13 Phase 5).  Same design and same
# bottom-up flow as chip_bottomup.buda (3x big2 + 3x mix2 + 100 top buses,
# 432 leaf blocks / 13320 nets, healing with negotiate_congestion only), with
# ONE extra line declaring the whole policy:
#
#   reserve_top_layers 2
#
# Counting DEEPEST-FIRST over intrinsic cell levels: the leaf cells (level 1,
# no interconnect of their own) get [lowest..M5], the big2/mix2 cell templates
# (level 2 — this is the band that bites, their cell-local buses) get
# [lowest..M9], and the top cell (level 3, past the argument list) stays
# UNRESTRICTED so the 100 cross-instance top buses keep M10/M11 to themselves.
# That is the BKM the whole feature exists to express, in one line instead of
# a set_cell_layer_cap per cell type.
#
# THE BAND MUST SCALE WITH THE STACK — which is why this vehicle says
# `reserve_top_layers 2` and not an absolute band.  It was originally
# written as `set_layer_caps_by_depth M3 M5` for the 6-layer stack, where
# [..M5] left M6/M7 (the top PAIR) to the top level.  The identical text on
# the 10-layer stack reserves SIX layers for a top level that needs two, and
# starves the cell templates: measured 3192 unplaced bits, against 1708 when
# the band is rescaled.  Measured alternatives on this stack, cell band:
# M5 -> 3192 unplaced, M7 -> 1898, M9 -> 1708, uncapped -> 1604.
# `reserve_top_layers 2` derives the M9 cap from the stack itself, so it
# stays correct if the stack grows again (byte-identical to the hand-written
# `set_layer_caps_by_depth M5 M9`: 358/1708/93).
#
# Note the leaf argument is a free choice here: the level-1 cells are true
# leaves with no cell-local bundles, so `M5 M9` and `M7 M9` produce byte-
# identical results.  Only the level-2 band bites in this design.
#
# The separation is visible in report_wirelength's per-layer breakdown: zero
# cell-template WL above M9, and M10/M11 exclusively top-level.  Compare
# against chip_bottomup.buda (identical but uncapped) for the §12 study.
source [file join $::corpus::root {chip/chip_tracks.tcl}]
buda::open_bdb {chip.bdb.sql}
buda::set_bottom_up {big2}
buda::set_bottom_up {mix2}
buda::align_bottom_up
buda::reserve_top_layers {2}
buda::derive_busterms {2}
buda::add_blocks_from_bdb {0}
buda::add_blocks_from_bdb {1} {skip}
buda::add_blocks_from_bdb {2} {skip}
buda::set_max_bundle_bits {auto}
buda::run_hier_bundler {depth} {2}
buda::generate_hier_topologies
buda::set_planner_param {healersAhead} {1}
buda::run_planner {hier} {5} {signal_tracks}
buda::run_nuts
buda::check_template_tracks {on_mismatch} {independent}
buda::run_detailed_nuts
buda::negotiate_congestion
buda::report_wl
buda::check_design
corpus::end [info script]   ;# `exit` in the original
return
